// Code generated by ent, DO NOT EDIT.

package locationlayout

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the locationlayout type in the database.
	Label = "location_layout"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCanvasWidth holds the string denoting the canvas_width field in the database.
	FieldCanvasWidth = "canvas_width"
	// FieldCanvasHeight holds the string denoting the canvas_height field in the database.
	FieldCanvasHeight = "canvas_height"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeElements holds the string denoting the elements edge name in mutations.
	EdgeElements = "elements"
	// Table holds the table name of the locationlayout in the database.
	Table = "location_layouts"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "location_layouts"
	// OwnerInverseTable is the table name for the Entity entity.
	// It exists in this package in order to avoid circular dependency with the "entity" package.
	OwnerInverseTable = "entities"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "entity_location_layout"
	// ElementsTable is the table that holds the elements relation/edge.
	ElementsTable = "location_layout_elements"
	// ElementsInverseTable is the table name for the LocationLayoutElement entity.
	// It exists in this package in order to avoid circular dependency with the "locationlayoutelement" package.
	ElementsInverseTable = "location_layout_elements"
	// ElementsColumn is the table column denoting the elements relation/edge.
	ElementsColumn = "location_layout_elements"
)

// Columns holds all SQL columns for locationlayout fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCanvasWidth,
	FieldCanvasHeight,
	FieldRevision,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "location_layouts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"entity_location_layout",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCanvasWidth holds the default value on creation for the "canvas_width" field.
	DefaultCanvasWidth int
	// CanvasWidthValidator is a validator for the "canvas_width" field. It is called by the builders before save.
	CanvasWidthValidator func(int) error
	// DefaultCanvasHeight holds the default value on creation for the "canvas_height" field.
	DefaultCanvasHeight int
	// CanvasHeightValidator is a validator for the "canvas_height" field. It is called by the builders before save.
	CanvasHeightValidator func(int) error
	// DefaultRevision holds the default value on creation for the "revision" field.
	DefaultRevision int
	// RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	RevisionValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the LocationLayout queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCanvasWidth orders the results by the canvas_width field.
func ByCanvasWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanvasWidth, opts...).ToFunc()
}

// ByCanvasHeight orders the results by the canvas_height field.
func ByCanvasHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanvasHeight, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByElementsCount orders the results by elements count.
func ByElementsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newElementsStep(), opts...)
	}
}

// ByElements orders the results by elements terms.
func ByElements(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newElementsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
	)
}
func newElementsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ElementsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ElementsTable, ElementsColumn),
	)
}
