// Code generated by ent, DO NOT EDIT.

package locationlayout

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldEQ(FieldUpdatedAt, v))
}

// CanvasWidth applies equality check predicate on the "canvas_width" field. It's identical to CanvasWidthEQ.
func CanvasWidth(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldEQ(FieldCanvasWidth, v))
}

// CanvasHeight applies equality check predicate on the "canvas_height" field. It's identical to CanvasHeightEQ.
func CanvasHeight(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldEQ(FieldCanvasHeight, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldEQ(FieldRevision, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldLTE(FieldUpdatedAt, v))
}

// CanvasWidthEQ applies the EQ predicate on the "canvas_width" field.
func CanvasWidthEQ(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldEQ(FieldCanvasWidth, v))
}

// CanvasWidthNEQ applies the NEQ predicate on the "canvas_width" field.
func CanvasWidthNEQ(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldNEQ(FieldCanvasWidth, v))
}

// CanvasWidthIn applies the In predicate on the "canvas_width" field.
func CanvasWidthIn(vs ...int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldIn(FieldCanvasWidth, vs...))
}

// CanvasWidthNotIn applies the NotIn predicate on the "canvas_width" field.
func CanvasWidthNotIn(vs ...int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldNotIn(FieldCanvasWidth, vs...))
}

// CanvasWidthGT applies the GT predicate on the "canvas_width" field.
func CanvasWidthGT(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldGT(FieldCanvasWidth, v))
}

// CanvasWidthGTE applies the GTE predicate on the "canvas_width" field.
func CanvasWidthGTE(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldGTE(FieldCanvasWidth, v))
}

// CanvasWidthLT applies the LT predicate on the "canvas_width" field.
func CanvasWidthLT(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldLT(FieldCanvasWidth, v))
}

// CanvasWidthLTE applies the LTE predicate on the "canvas_width" field.
func CanvasWidthLTE(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldLTE(FieldCanvasWidth, v))
}

// CanvasHeightEQ applies the EQ predicate on the "canvas_height" field.
func CanvasHeightEQ(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldEQ(FieldCanvasHeight, v))
}

// CanvasHeightNEQ applies the NEQ predicate on the "canvas_height" field.
func CanvasHeightNEQ(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldNEQ(FieldCanvasHeight, v))
}

// CanvasHeightIn applies the In predicate on the "canvas_height" field.
func CanvasHeightIn(vs ...int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldIn(FieldCanvasHeight, vs...))
}

// CanvasHeightNotIn applies the NotIn predicate on the "canvas_height" field.
func CanvasHeightNotIn(vs ...int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldNotIn(FieldCanvasHeight, vs...))
}

// CanvasHeightGT applies the GT predicate on the "canvas_height" field.
func CanvasHeightGT(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldGT(FieldCanvasHeight, v))
}

// CanvasHeightGTE applies the GTE predicate on the "canvas_height" field.
func CanvasHeightGTE(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldGTE(FieldCanvasHeight, v))
}

// CanvasHeightLT applies the LT predicate on the "canvas_height" field.
func CanvasHeightLT(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldLT(FieldCanvasHeight, v))
}

// CanvasHeightLTE applies the LTE predicate on the "canvas_height" field.
func CanvasHeightLTE(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldLTE(FieldCanvasHeight, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int) predicate.LocationLayout {
	return predicate.LocationLayout(sql.FieldLTE(FieldRevision, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.LocationLayout {
	return predicate.LocationLayout(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.Entity) predicate.LocationLayout {
	return predicate.LocationLayout(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasElements applies the HasEdge predicate on the "elements" edge.
func HasElements() predicate.LocationLayout {
	return predicate.LocationLayout(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ElementsTable, ElementsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasElementsWith applies the HasEdge predicate on the "elements" edge with a given conditions (other predicates).
func HasElementsWith(preds ...predicate.LocationLayoutElement) predicate.LocationLayout {
	return predicate.LocationLayout(func(s *sql.Selector) {
		step := newElementsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LocationLayout) predicate.LocationLayout {
	return predicate.LocationLayout(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LocationLayout) predicate.LocationLayout {
	return predicate.LocationLayout(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LocationLayout) predicate.LocationLayout {
	return predicate.LocationLayout(sql.NotPredicates(p))
}
