// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entitystocktransaction"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
)

// EntityStockTransaction is the model entity for the EntityStockTransaction schema.
type EntityStockTransaction struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID uuid.UUID `json:"group_id,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID uuid.UUID `json:"entity_id,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID *uuid.UUID `json:"actor_id,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation entitystocktransaction.Operation `json:"operation,omitempty"`
	// Workflow holds the value of the "workflow" field.
	Workflow string `json:"workflow,omitempty"`
	// SourceLocationID holds the value of the "source_location_id" field.
	SourceLocationID *uuid.UUID `json:"source_location_id,omitempty"`
	// DestinationLocationID holds the value of the "destination_location_id" field.
	DestinationLocationID *uuid.UUID `json:"destination_location_id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity float64 `json:"quantity,omitempty"`
	// BeforeTotal holds the value of the "before_total" field.
	BeforeTotal float64 `json:"before_total,omitempty"`
	// AfterTotal holds the value of the "after_total" field.
	AfterTotal float64 `json:"after_total,omitempty"`
	// SourceBefore holds the value of the "source_before" field.
	SourceBefore *float64 `json:"source_before,omitempty"`
	// SourceAfter holds the value of the "source_after" field.
	SourceAfter *float64 `json:"source_after,omitempty"`
	// DestinationBefore holds the value of the "destination_before" field.
	DestinationBefore *float64 `json:"destination_before,omitempty"`
	// DestinationAfter holds the value of the "destination_after" field.
	DestinationAfter *float64 `json:"destination_after,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// RequestHash holds the value of the "request_hash" field.
	RequestHash string `json:"request_hash,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EntityStockTransactionQuery when eager-loading is set.
	Edges        EntityStockTransactionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EntityStockTransactionEdges holds the relations/edges for other nodes in the graph.
type EntityStockTransactionEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Entity holds the value of the entity edge.
	Entity *Entity `json:"entity,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntityStockTransactionEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// EntityOrErr returns the Entity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntityStockTransactionEdges) EntityOrErr() (*Entity, error) {
	if e.Entity != nil {
		return e.Entity, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: entity.Label}
	}
	return nil, &NotLoadedError{edge: "entity"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntityStockTransaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entitystocktransaction.FieldActorID, entitystocktransaction.FieldSourceLocationID, entitystocktransaction.FieldDestinationLocationID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case entitystocktransaction.FieldQuantity, entitystocktransaction.FieldBeforeTotal, entitystocktransaction.FieldAfterTotal, entitystocktransaction.FieldSourceBefore, entitystocktransaction.FieldSourceAfter, entitystocktransaction.FieldDestinationBefore, entitystocktransaction.FieldDestinationAfter:
			values[i] = new(sql.NullFloat64)
		case entitystocktransaction.FieldOperation, entitystocktransaction.FieldWorkflow, entitystocktransaction.FieldReason, entitystocktransaction.FieldIdempotencyKey, entitystocktransaction.FieldRequestHash:
			values[i] = new(sql.NullString)
		case entitystocktransaction.FieldCreatedAt, entitystocktransaction.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case entitystocktransaction.FieldID, entitystocktransaction.FieldGroupID, entitystocktransaction.FieldEntityID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntityStockTransaction fields.
func (_m *EntityStockTransaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entitystocktransaction.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case entitystocktransaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case entitystocktransaction.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case entitystocktransaction.FieldGroupID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value != nil {
				_m.GroupID = *value
			}
		case entitystocktransaction.FieldEntityID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value != nil {
				_m.EntityID = *value
			}
		case entitystocktransaction.FieldActorID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value.Valid {
				_m.ActorID = new(uuid.UUID)
				*_m.ActorID = *value.S.(*uuid.UUID)
			}
		case entitystocktransaction.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = entitystocktransaction.Operation(value.String)
			}
		case entitystocktransaction.FieldWorkflow:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workflow", values[i])
			} else if value.Valid {
				_m.Workflow = value.String
			}
		case entitystocktransaction.FieldSourceLocationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field source_location_id", values[i])
			} else if value.Valid {
				_m.SourceLocationID = new(uuid.UUID)
				*_m.SourceLocationID = *value.S.(*uuid.UUID)
			}
		case entitystocktransaction.FieldDestinationLocationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field destination_location_id", values[i])
			} else if value.Valid {
				_m.DestinationLocationID = new(uuid.UUID)
				*_m.DestinationLocationID = *value.S.(*uuid.UUID)
			}
		case entitystocktransaction.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Float64
			}
		case entitystocktransaction.FieldBeforeTotal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field before_total", values[i])
			} else if value.Valid {
				_m.BeforeTotal = value.Float64
			}
		case entitystocktransaction.FieldAfterTotal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field after_total", values[i])
			} else if value.Valid {
				_m.AfterTotal = value.Float64
			}
		case entitystocktransaction.FieldSourceBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field source_before", values[i])
			} else if value.Valid {
				_m.SourceBefore = new(float64)
				*_m.SourceBefore = value.Float64
			}
		case entitystocktransaction.FieldSourceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field source_after", values[i])
			} else if value.Valid {
				_m.SourceAfter = new(float64)
				*_m.SourceAfter = value.Float64
			}
		case entitystocktransaction.FieldDestinationBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field destination_before", values[i])
			} else if value.Valid {
				_m.DestinationBefore = new(float64)
				*_m.DestinationBefore = value.Float64
			}
		case entitystocktransaction.FieldDestinationAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field destination_after", values[i])
			} else if value.Valid {
				_m.DestinationAfter = new(float64)
				*_m.DestinationAfter = value.Float64
			}
		case entitystocktransaction.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case entitystocktransaction.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case entitystocktransaction.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				_m.RequestHash = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EntityStockTransaction.
// This includes values selected through modifiers, order, etc.
func (_m *EntityStockTransaction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the EntityStockTransaction entity.
func (_m *EntityStockTransaction) QueryGroup() *GroupQuery {
	return NewEntityStockTransactionClient(_m.config).QueryGroup(_m)
}

// QueryEntity queries the "entity" edge of the EntityStockTransaction entity.
func (_m *EntityStockTransaction) QueryEntity() *EntityQuery {
	return NewEntityStockTransactionClient(_m.config).QueryEntity(_m)
}

// Update returns a builder for updating this EntityStockTransaction.
// Note that you need to call EntityStockTransaction.Unwrap() before calling this method if this EntityStockTransaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EntityStockTransaction) Update() *EntityStockTransactionUpdateOne {
	return NewEntityStockTransactionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EntityStockTransaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EntityStockTransaction) Unwrap() *EntityStockTransaction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntityStockTransaction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EntityStockTransaction) String() string {
	var builder strings.Builder
	builder.WriteString("EntityStockTransaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntityID))
	builder.WriteString(", ")
	if v := _m.ActorID; v != nil {
		builder.WriteString("actor_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Operation))
	builder.WriteString(", ")
	builder.WriteString("workflow=")
	builder.WriteString(_m.Workflow)
	builder.WriteString(", ")
	if v := _m.SourceLocationID; v != nil {
		builder.WriteString("source_location_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DestinationLocationID; v != nil {
		builder.WriteString("destination_location_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("before_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.BeforeTotal))
	builder.WriteString(", ")
	builder.WriteString("after_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.AfterTotal))
	builder.WriteString(", ")
	if v := _m.SourceBefore; v != nil {
		builder.WriteString("source_before=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SourceAfter; v != nil {
		builder.WriteString("source_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DestinationBefore; v != nil {
		builder.WriteString("destination_before=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DestinationAfter; v != nil {
		builder.WriteString("destination_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(_m.RequestHash)
	builder.WriteByte(')')
	return builder.String()
}

// EntityStockTransactions is a parsable slice of EntityStockTransaction.
type EntityStockTransactions []*EntityStockTransaction
