// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entitystocktransaction"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
)

// EntityStockTransactionCreate is the builder for creating a EntityStockTransaction entity.
type EntityStockTransactionCreate struct {
	config
	mutation *EntityStockTransactionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *EntityStockTransactionCreate) SetCreatedAt(v time.Time) *EntityStockTransactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EntityStockTransactionCreate) SetNillableCreatedAt(v *time.Time) *EntityStockTransactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EntityStockTransactionCreate) SetUpdatedAt(v time.Time) *EntityStockTransactionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EntityStockTransactionCreate) SetNillableUpdatedAt(v *time.Time) *EntityStockTransactionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *EntityStockTransactionCreate) SetGroupID(v uuid.UUID) *EntityStockTransactionCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetEntityID sets the "entity_id" field.
func (_c *EntityStockTransactionCreate) SetEntityID(v uuid.UUID) *EntityStockTransactionCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *EntityStockTransactionCreate) SetActorID(v uuid.UUID) *EntityStockTransactionCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *EntityStockTransactionCreate) SetNillableActorID(v *uuid.UUID) *EntityStockTransactionCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetOperation sets the "operation" field.
func (_c *EntityStockTransactionCreate) SetOperation(v entitystocktransaction.Operation) *EntityStockTransactionCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetWorkflow sets the "workflow" field.
func (_c *EntityStockTransactionCreate) SetWorkflow(v string) *EntityStockTransactionCreate {
	_c.mutation.SetWorkflow(v)
	return _c
}

// SetNillableWorkflow sets the "workflow" field if the given value is not nil.
func (_c *EntityStockTransactionCreate) SetNillableWorkflow(v *string) *EntityStockTransactionCreate {
	if v != nil {
		_c.SetWorkflow(*v)
	}
	return _c
}

// SetSourceLocationID sets the "source_location_id" field.
func (_c *EntityStockTransactionCreate) SetSourceLocationID(v uuid.UUID) *EntityStockTransactionCreate {
	_c.mutation.SetSourceLocationID(v)
	return _c
}

// SetNillableSourceLocationID sets the "source_location_id" field if the given value is not nil.
func (_c *EntityStockTransactionCreate) SetNillableSourceLocationID(v *uuid.UUID) *EntityStockTransactionCreate {
	if v != nil {
		_c.SetSourceLocationID(*v)
	}
	return _c
}

// SetDestinationLocationID sets the "destination_location_id" field.
func (_c *EntityStockTransactionCreate) SetDestinationLocationID(v uuid.UUID) *EntityStockTransactionCreate {
	_c.mutation.SetDestinationLocationID(v)
	return _c
}

// SetNillableDestinationLocationID sets the "destination_location_id" field if the given value is not nil.
func (_c *EntityStockTransactionCreate) SetNillableDestinationLocationID(v *uuid.UUID) *EntityStockTransactionCreate {
	if v != nil {
		_c.SetDestinationLocationID(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *EntityStockTransactionCreate) SetQuantity(v float64) *EntityStockTransactionCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetBeforeTotal sets the "before_total" field.
func (_c *EntityStockTransactionCreate) SetBeforeTotal(v float64) *EntityStockTransactionCreate {
	_c.mutation.SetBeforeTotal(v)
	return _c
}

// SetAfterTotal sets the "after_total" field.
func (_c *EntityStockTransactionCreate) SetAfterTotal(v float64) *EntityStockTransactionCreate {
	_c.mutation.SetAfterTotal(v)
	return _c
}

// SetSourceBefore sets the "source_before" field.
func (_c *EntityStockTransactionCreate) SetSourceBefore(v float64) *EntityStockTransactionCreate {
	_c.mutation.SetSourceBefore(v)
	return _c
}

// SetNillableSourceBefore sets the "source_before" field if the given value is not nil.
func (_c *EntityStockTransactionCreate) SetNillableSourceBefore(v *float64) *EntityStockTransactionCreate {
	if v != nil {
		_c.SetSourceBefore(*v)
	}
	return _c
}

// SetSourceAfter sets the "source_after" field.
func (_c *EntityStockTransactionCreate) SetSourceAfter(v float64) *EntityStockTransactionCreate {
	_c.mutation.SetSourceAfter(v)
	return _c
}

// SetNillableSourceAfter sets the "source_after" field if the given value is not nil.
func (_c *EntityStockTransactionCreate) SetNillableSourceAfter(v *float64) *EntityStockTransactionCreate {
	if v != nil {
		_c.SetSourceAfter(*v)
	}
	return _c
}

// SetDestinationBefore sets the "destination_before" field.
func (_c *EntityStockTransactionCreate) SetDestinationBefore(v float64) *EntityStockTransactionCreate {
	_c.mutation.SetDestinationBefore(v)
	return _c
}

// SetNillableDestinationBefore sets the "destination_before" field if the given value is not nil.
func (_c *EntityStockTransactionCreate) SetNillableDestinationBefore(v *float64) *EntityStockTransactionCreate {
	if v != nil {
		_c.SetDestinationBefore(*v)
	}
	return _c
}

// SetDestinationAfter sets the "destination_after" field.
func (_c *EntityStockTransactionCreate) SetDestinationAfter(v float64) *EntityStockTransactionCreate {
	_c.mutation.SetDestinationAfter(v)
	return _c
}

// SetNillableDestinationAfter sets the "destination_after" field if the given value is not nil.
func (_c *EntityStockTransactionCreate) SetNillableDestinationAfter(v *float64) *EntityStockTransactionCreate {
	if v != nil {
		_c.SetDestinationAfter(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *EntityStockTransactionCreate) SetReason(v string) *EntityStockTransactionCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *EntityStockTransactionCreate) SetNillableReason(v *string) *EntityStockTransactionCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *EntityStockTransactionCreate) SetIdempotencyKey(v string) *EntityStockTransactionCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetRequestHash sets the "request_hash" field.
func (_c *EntityStockTransactionCreate) SetRequestHash(v string) *EntityStockTransactionCreate {
	_c.mutation.SetRequestHash(v)
	return _c
}

// SetID sets the "id" field.
func (_c *EntityStockTransactionCreate) SetID(v uuid.UUID) *EntityStockTransactionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EntityStockTransactionCreate) SetNillableID(v *uuid.UUID) *EntityStockTransactionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *EntityStockTransactionCreate) SetGroup(v *Group) *EntityStockTransactionCreate {
	return _c.SetGroupID(v.ID)
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_c *EntityStockTransactionCreate) SetEntity(v *Entity) *EntityStockTransactionCreate {
	return _c.SetEntityID(v.ID)
}

// Mutation returns the EntityStockTransactionMutation object of the builder.
func (_c *EntityStockTransactionCreate) Mutation() *EntityStockTransactionMutation {
	return _c.mutation
}

// Save creates the EntityStockTransaction in the database.
func (_c *EntityStockTransactionCreate) Save(ctx context.Context) (*EntityStockTransaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntityStockTransactionCreate) SaveX(ctx context.Context) *EntityStockTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityStockTransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityStockTransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EntityStockTransactionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := entitystocktransaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := entitystocktransaction.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := entitystocktransaction.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntityStockTransactionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EntityStockTransaction.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EntityStockTransaction.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "EntityStockTransaction.group_id"`)}
	}
	if _, ok := _c.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "EntityStockTransaction.entity_id"`)}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "EntityStockTransaction.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := entitystocktransaction.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "EntityStockTransaction.operation": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Workflow(); ok {
		if err := entitystocktransaction.WorkflowValidator(v); err != nil {
			return &ValidationError{Name: "workflow", err: fmt.Errorf(`ent: validator failed for field "EntityStockTransaction.workflow": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "EntityStockTransaction.quantity"`)}
	}
	if _, ok := _c.mutation.BeforeTotal(); !ok {
		return &ValidationError{Name: "before_total", err: errors.New(`ent: missing required field "EntityStockTransaction.before_total"`)}
	}
	if _, ok := _c.mutation.AfterTotal(); !ok {
		return &ValidationError{Name: "after_total", err: errors.New(`ent: missing required field "EntityStockTransaction.after_total"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := entitystocktransaction.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "EntityStockTransaction.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "EntityStockTransaction.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := entitystocktransaction.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "EntityStockTransaction.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestHash(); !ok {
		return &ValidationError{Name: "request_hash", err: errors.New(`ent: missing required field "EntityStockTransaction.request_hash"`)}
	}
	if v, ok := _c.mutation.RequestHash(); ok {
		if err := entitystocktransaction.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "EntityStockTransaction.request_hash": %w`, err)}
		}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "EntityStockTransaction.group"`)}
	}
	if len(_c.mutation.EntityIDs()) == 0 {
		return &ValidationError{Name: "entity", err: errors.New(`ent: missing required edge "EntityStockTransaction.entity"`)}
	}
	return nil
}

func (_c *EntityStockTransactionCreate) sqlSave(ctx context.Context) (*EntityStockTransaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntityStockTransactionCreate) createSpec() (*EntityStockTransaction, *sqlgraph.CreateSpec) {
	var (
		_node = &EntityStockTransaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entitystocktransaction.Table, sqlgraph.NewFieldSpec(entitystocktransaction.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(entitystocktransaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(entitystocktransaction.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(entitystocktransaction.FieldActorID, field.TypeUUID, value)
		_node.ActorID = &value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(entitystocktransaction.FieldOperation, field.TypeEnum, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.Workflow(); ok {
		_spec.SetField(entitystocktransaction.FieldWorkflow, field.TypeString, value)
		_node.Workflow = value
	}
	if value, ok := _c.mutation.SourceLocationID(); ok {
		_spec.SetField(entitystocktransaction.FieldSourceLocationID, field.TypeUUID, value)
		_node.SourceLocationID = &value
	}
	if value, ok := _c.mutation.DestinationLocationID(); ok {
		_spec.SetField(entitystocktransaction.FieldDestinationLocationID, field.TypeUUID, value)
		_node.DestinationLocationID = &value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(entitystocktransaction.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.BeforeTotal(); ok {
		_spec.SetField(entitystocktransaction.FieldBeforeTotal, field.TypeFloat64, value)
		_node.BeforeTotal = value
	}
	if value, ok := _c.mutation.AfterTotal(); ok {
		_spec.SetField(entitystocktransaction.FieldAfterTotal, field.TypeFloat64, value)
		_node.AfterTotal = value
	}
	if value, ok := _c.mutation.SourceBefore(); ok {
		_spec.SetField(entitystocktransaction.FieldSourceBefore, field.TypeFloat64, value)
		_node.SourceBefore = &value
	}
	if value, ok := _c.mutation.SourceAfter(); ok {
		_spec.SetField(entitystocktransaction.FieldSourceAfter, field.TypeFloat64, value)
		_node.SourceAfter = &value
	}
	if value, ok := _c.mutation.DestinationBefore(); ok {
		_spec.SetField(entitystocktransaction.FieldDestinationBefore, field.TypeFloat64, value)
		_node.DestinationBefore = &value
	}
	if value, ok := _c.mutation.DestinationAfter(); ok {
		_spec.SetField(entitystocktransaction.FieldDestinationAfter, field.TypeFloat64, value)
		_node.DestinationAfter = &value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(entitystocktransaction.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(entitystocktransaction.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.RequestHash(); ok {
		_spec.SetField(entitystocktransaction.FieldRequestHash, field.TypeString, value)
		_node.RequestHash = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystocktransaction.GroupTable,
			Columns: []string{entitystocktransaction.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystocktransaction.EntityTable,
			Columns: []string{entitystocktransaction.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EntityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EntityStockTransactionCreateBulk is the builder for creating many EntityStockTransaction entities in bulk.
type EntityStockTransactionCreateBulk struct {
	config
	err      error
	builders []*EntityStockTransactionCreate
}

// Save creates the EntityStockTransaction entities in the database.
func (_c *EntityStockTransactionCreateBulk) Save(ctx context.Context) ([]*EntityStockTransaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EntityStockTransaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntityStockTransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntityStockTransactionCreateBulk) SaveX(ctx context.Context) []*EntityStockTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityStockTransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityStockTransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
