// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entitystockallocation"
)

// EntityStockAllocation is the model entity for the EntityStockAllocation schema.
type EntityStockAllocation struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID uuid.UUID `json:"entity_id,omitempty"`
	// LocationID holds the value of the "location_id" field.
	LocationID *uuid.UUID `json:"location_id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity float64 `json:"quantity,omitempty"`
	// IsDefault holds the value of the "is_default" field.
	IsDefault bool `json:"is_default,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EntityStockAllocationQuery when eager-loading is set.
	Edges        EntityStockAllocationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EntityStockAllocationEdges holds the relations/edges for other nodes in the graph.
type EntityStockAllocationEdges struct {
	// Entity holds the value of the entity edge.
	Entity *Entity `json:"entity,omitempty"`
	// Location holds the value of the location edge.
	Location *Entity `json:"location,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// EntityOrErr returns the Entity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntityStockAllocationEdges) EntityOrErr() (*Entity, error) {
	if e.Entity != nil {
		return e.Entity, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: entity.Label}
	}
	return nil, &NotLoadedError{edge: "entity"}
}

// LocationOrErr returns the Location value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntityStockAllocationEdges) LocationOrErr() (*Entity, error) {
	if e.Location != nil {
		return e.Location, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: entity.Label}
	}
	return nil, &NotLoadedError{edge: "location"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntityStockAllocation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entitystockallocation.FieldLocationID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case entitystockallocation.FieldIsDefault:
			values[i] = new(sql.NullBool)
		case entitystockallocation.FieldQuantity:
			values[i] = new(sql.NullFloat64)
		case entitystockallocation.FieldCreatedAt, entitystockallocation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case entitystockallocation.FieldID, entitystockallocation.FieldEntityID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntityStockAllocation fields.
func (_m *EntityStockAllocation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entitystockallocation.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case entitystockallocation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case entitystockallocation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case entitystockallocation.FieldEntityID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value != nil {
				_m.EntityID = *value
			}
		case entitystockallocation.FieldLocationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field location_id", values[i])
			} else if value.Valid {
				_m.LocationID = new(uuid.UUID)
				*_m.LocationID = *value.S.(*uuid.UUID)
			}
		case entitystockallocation.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Float64
			}
		case entitystockallocation.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EntityStockAllocation.
// This includes values selected through modifiers, order, etc.
func (_m *EntityStockAllocation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEntity queries the "entity" edge of the EntityStockAllocation entity.
func (_m *EntityStockAllocation) QueryEntity() *EntityQuery {
	return NewEntityStockAllocationClient(_m.config).QueryEntity(_m)
}

// QueryLocation queries the "location" edge of the EntityStockAllocation entity.
func (_m *EntityStockAllocation) QueryLocation() *EntityQuery {
	return NewEntityStockAllocationClient(_m.config).QueryLocation(_m)
}

// Update returns a builder for updating this EntityStockAllocation.
// Note that you need to call EntityStockAllocation.Unwrap() before calling this method if this EntityStockAllocation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EntityStockAllocation) Update() *EntityStockAllocationUpdateOne {
	return NewEntityStockAllocationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EntityStockAllocation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EntityStockAllocation) Unwrap() *EntityStockAllocation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntityStockAllocation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EntityStockAllocation) String() string {
	var builder strings.Builder
	builder.WriteString("EntityStockAllocation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntityID))
	builder.WriteString(", ")
	if v := _m.LocationID; v != nil {
		builder.WriteString("location_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteByte(')')
	return builder.String()
}

// EntityStockAllocations is a parsable slice of EntityStockAllocation.
type EntityStockAllocations []*EntityStockAllocation
