// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entitystockallocation"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// EntityStockAllocationUpdate is the builder for updating EntityStockAllocation entities.
type EntityStockAllocationUpdate struct {
	config
	hooks    []Hook
	mutation *EntityStockAllocationMutation
}

// Where appends a list predicates to the EntityStockAllocationUpdate builder.
func (_u *EntityStockAllocationUpdate) Where(ps ...predicate.EntityStockAllocation) *EntityStockAllocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntityStockAllocationUpdate) SetUpdatedAt(v time.Time) *EntityStockAllocationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *EntityStockAllocationUpdate) SetEntityID(v uuid.UUID) *EntityStockAllocationUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *EntityStockAllocationUpdate) SetNillableEntityID(v *uuid.UUID) *EntityStockAllocationUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetLocationID sets the "location_id" field.
func (_u *EntityStockAllocationUpdate) SetLocationID(v uuid.UUID) *EntityStockAllocationUpdate {
	_u.mutation.SetLocationID(v)
	return _u
}

// SetNillableLocationID sets the "location_id" field if the given value is not nil.
func (_u *EntityStockAllocationUpdate) SetNillableLocationID(v *uuid.UUID) *EntityStockAllocationUpdate {
	if v != nil {
		_u.SetLocationID(*v)
	}
	return _u
}

// ClearLocationID clears the value of the "location_id" field.
func (_u *EntityStockAllocationUpdate) ClearLocationID() *EntityStockAllocationUpdate {
	_u.mutation.ClearLocationID()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *EntityStockAllocationUpdate) SetQuantity(v float64) *EntityStockAllocationUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *EntityStockAllocationUpdate) SetNillableQuantity(v *float64) *EntityStockAllocationUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *EntityStockAllocationUpdate) AddQuantity(v float64) *EntityStockAllocationUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *EntityStockAllocationUpdate) SetIsDefault(v bool) *EntityStockAllocationUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *EntityStockAllocationUpdate) SetNillableIsDefault(v *bool) *EntityStockAllocationUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_u *EntityStockAllocationUpdate) SetEntity(v *Entity) *EntityStockAllocationUpdate {
	return _u.SetEntityID(v.ID)
}

// SetLocation sets the "location" edge to the Entity entity.
func (_u *EntityStockAllocationUpdate) SetLocation(v *Entity) *EntityStockAllocationUpdate {
	return _u.SetLocationID(v.ID)
}

// Mutation returns the EntityStockAllocationMutation object of the builder.
func (_u *EntityStockAllocationUpdate) Mutation() *EntityStockAllocationMutation {
	return _u.mutation
}

// ClearEntity clears the "entity" edge to the Entity entity.
func (_u *EntityStockAllocationUpdate) ClearEntity() *EntityStockAllocationUpdate {
	_u.mutation.ClearEntity()
	return _u
}

// ClearLocation clears the "location" edge to the Entity entity.
func (_u *EntityStockAllocationUpdate) ClearLocation() *EntityStockAllocationUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntityStockAllocationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityStockAllocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntityStockAllocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityStockAllocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntityStockAllocationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entitystockallocation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityStockAllocationUpdate) check() error {
	if _u.mutation.EntityCleared() && len(_u.mutation.EntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityStockAllocation.entity"`)
	}
	return nil
}

func (_u *EntityStockAllocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entitystockallocation.Table, entitystockallocation.Columns, sqlgraph.NewFieldSpec(entitystockallocation.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entitystockallocation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(entitystockallocation.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(entitystockallocation.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(entitystockallocation.FieldIsDefault, field.TypeBool, value)
	}
	if _u.mutation.EntityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystockallocation.EntityTable,
			Columns: []string{entitystockallocation.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystockallocation.EntityTable,
			Columns: []string{entitystockallocation.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystockallocation.LocationTable,
			Columns: []string{entitystockallocation.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystockallocation.LocationTable,
			Columns: []string{entitystockallocation.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitystockallocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntityStockAllocationUpdateOne is the builder for updating a single EntityStockAllocation entity.
type EntityStockAllocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntityStockAllocationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntityStockAllocationUpdateOne) SetUpdatedAt(v time.Time) *EntityStockAllocationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *EntityStockAllocationUpdateOne) SetEntityID(v uuid.UUID) *EntityStockAllocationUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *EntityStockAllocationUpdateOne) SetNillableEntityID(v *uuid.UUID) *EntityStockAllocationUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetLocationID sets the "location_id" field.
func (_u *EntityStockAllocationUpdateOne) SetLocationID(v uuid.UUID) *EntityStockAllocationUpdateOne {
	_u.mutation.SetLocationID(v)
	return _u
}

// SetNillableLocationID sets the "location_id" field if the given value is not nil.
func (_u *EntityStockAllocationUpdateOne) SetNillableLocationID(v *uuid.UUID) *EntityStockAllocationUpdateOne {
	if v != nil {
		_u.SetLocationID(*v)
	}
	return _u
}

// ClearLocationID clears the value of the "location_id" field.
func (_u *EntityStockAllocationUpdateOne) ClearLocationID() *EntityStockAllocationUpdateOne {
	_u.mutation.ClearLocationID()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *EntityStockAllocationUpdateOne) SetQuantity(v float64) *EntityStockAllocationUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *EntityStockAllocationUpdateOne) SetNillableQuantity(v *float64) *EntityStockAllocationUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *EntityStockAllocationUpdateOne) AddQuantity(v float64) *EntityStockAllocationUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *EntityStockAllocationUpdateOne) SetIsDefault(v bool) *EntityStockAllocationUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *EntityStockAllocationUpdateOne) SetNillableIsDefault(v *bool) *EntityStockAllocationUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_u *EntityStockAllocationUpdateOne) SetEntity(v *Entity) *EntityStockAllocationUpdateOne {
	return _u.SetEntityID(v.ID)
}

// SetLocation sets the "location" edge to the Entity entity.
func (_u *EntityStockAllocationUpdateOne) SetLocation(v *Entity) *EntityStockAllocationUpdateOne {
	return _u.SetLocationID(v.ID)
}

// Mutation returns the EntityStockAllocationMutation object of the builder.
func (_u *EntityStockAllocationUpdateOne) Mutation() *EntityStockAllocationMutation {
	return _u.mutation
}

// ClearEntity clears the "entity" edge to the Entity entity.
func (_u *EntityStockAllocationUpdateOne) ClearEntity() *EntityStockAllocationUpdateOne {
	_u.mutation.ClearEntity()
	return _u
}

// ClearLocation clears the "location" edge to the Entity entity.
func (_u *EntityStockAllocationUpdateOne) ClearLocation() *EntityStockAllocationUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// Where appends a list predicates to the EntityStockAllocationUpdate builder.
func (_u *EntityStockAllocationUpdateOne) Where(ps ...predicate.EntityStockAllocation) *EntityStockAllocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntityStockAllocationUpdateOne) Select(field string, fields ...string) *EntityStockAllocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EntityStockAllocation entity.
func (_u *EntityStockAllocationUpdateOne) Save(ctx context.Context) (*EntityStockAllocation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityStockAllocationUpdateOne) SaveX(ctx context.Context) *EntityStockAllocation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntityStockAllocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityStockAllocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntityStockAllocationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entitystockallocation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityStockAllocationUpdateOne) check() error {
	if _u.mutation.EntityCleared() && len(_u.mutation.EntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityStockAllocation.entity"`)
	}
	return nil
}

func (_u *EntityStockAllocationUpdateOne) sqlSave(ctx context.Context) (_node *EntityStockAllocation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entitystockallocation.Table, entitystockallocation.Columns, sqlgraph.NewFieldSpec(entitystockallocation.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EntityStockAllocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entitystockallocation.FieldID)
		for _, f := range fields {
			if !entitystockallocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entitystockallocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entitystockallocation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(entitystockallocation.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(entitystockallocation.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(entitystockallocation.FieldIsDefault, field.TypeBool, value)
	}
	if _u.mutation.EntityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystockallocation.EntityTable,
			Columns: []string{entitystockallocation.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystockallocation.EntityTable,
			Columns: []string{entitystockallocation.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystockallocation.LocationTable,
			Columns: []string{entitystockallocation.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystockallocation.LocationTable,
			Columns: []string{entitystockallocation.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EntityStockAllocation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitystockallocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
