// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entitystockallocation"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// EntityStockAllocationDelete is the builder for deleting a EntityStockAllocation entity.
type EntityStockAllocationDelete struct {
	config
	hooks    []Hook
	mutation *EntityStockAllocationMutation
}

// Where appends a list predicates to the EntityStockAllocationDelete builder.
func (_d *EntityStockAllocationDelete) Where(ps ...predicate.EntityStockAllocation) *EntityStockAllocationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EntityStockAllocationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EntityStockAllocationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EntityStockAllocationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(entitystockallocation.Table, sqlgraph.NewFieldSpec(entitystockallocation.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EntityStockAllocationDeleteOne is the builder for deleting a single EntityStockAllocation entity.
type EntityStockAllocationDeleteOne struct {
	_d *EntityStockAllocationDelete
}

// Where appends a list predicates to the EntityStockAllocationDelete builder.
func (_d *EntityStockAllocationDeleteOne) Where(ps ...predicate.EntityStockAllocation) *EntityStockAllocationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EntityStockAllocationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{entitystockallocation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EntityStockAllocationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
