// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entitystocktransaction"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// EntityStockTransactionUpdate is the builder for updating EntityStockTransaction entities.
type EntityStockTransactionUpdate struct {
	config
	hooks    []Hook
	mutation *EntityStockTransactionMutation
}

// Where appends a list predicates to the EntityStockTransactionUpdate builder.
func (_u *EntityStockTransactionUpdate) Where(ps ...predicate.EntityStockTransaction) *EntityStockTransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntityStockTransactionUpdate) SetUpdatedAt(v time.Time) *EntityStockTransactionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *EntityStockTransactionUpdate) SetGroupID(v uuid.UUID) *EntityStockTransactionUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *EntityStockTransactionUpdate) SetNillableGroupID(v *uuid.UUID) *EntityStockTransactionUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *EntityStockTransactionUpdate) SetEntityID(v uuid.UUID) *EntityStockTransactionUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *EntityStockTransactionUpdate) SetNillableEntityID(v *uuid.UUID) *EntityStockTransactionUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *EntityStockTransactionUpdate) SetGroup(v *Group) *EntityStockTransactionUpdate {
	return _u.SetGroupID(v.ID)
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_u *EntityStockTransactionUpdate) SetEntity(v *Entity) *EntityStockTransactionUpdate {
	return _u.SetEntityID(v.ID)
}

// Mutation returns the EntityStockTransactionMutation object of the builder.
func (_u *EntityStockTransactionUpdate) Mutation() *EntityStockTransactionMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *EntityStockTransactionUpdate) ClearGroup() *EntityStockTransactionUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearEntity clears the "entity" edge to the Entity entity.
func (_u *EntityStockTransactionUpdate) ClearEntity() *EntityStockTransactionUpdate {
	_u.mutation.ClearEntity()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntityStockTransactionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityStockTransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntityStockTransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityStockTransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntityStockTransactionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entitystocktransaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityStockTransactionUpdate) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityStockTransaction.group"`)
	}
	if _u.mutation.EntityCleared() && len(_u.mutation.EntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityStockTransaction.entity"`)
	}
	return nil
}

func (_u *EntityStockTransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entitystocktransaction.Table, entitystocktransaction.Columns, sqlgraph.NewFieldSpec(entitystocktransaction.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entitystocktransaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActorIDCleared() {
		_spec.ClearField(entitystocktransaction.FieldActorID, field.TypeUUID)
	}
	if _u.mutation.WorkflowCleared() {
		_spec.ClearField(entitystocktransaction.FieldWorkflow, field.TypeString)
	}
	if _u.mutation.SourceLocationIDCleared() {
		_spec.ClearField(entitystocktransaction.FieldSourceLocationID, field.TypeUUID)
	}
	if _u.mutation.DestinationLocationIDCleared() {
		_spec.ClearField(entitystocktransaction.FieldDestinationLocationID, field.TypeUUID)
	}
	if _u.mutation.SourceBeforeCleared() {
		_spec.ClearField(entitystocktransaction.FieldSourceBefore, field.TypeFloat64)
	}
	if _u.mutation.SourceAfterCleared() {
		_spec.ClearField(entitystocktransaction.FieldSourceAfter, field.TypeFloat64)
	}
	if _u.mutation.DestinationBeforeCleared() {
		_spec.ClearField(entitystocktransaction.FieldDestinationBefore, field.TypeFloat64)
	}
	if _u.mutation.DestinationAfterCleared() {
		_spec.ClearField(entitystocktransaction.FieldDestinationAfter, field.TypeFloat64)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(entitystocktransaction.FieldReason, field.TypeString)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystocktransaction.GroupTable,
			Columns: []string{entitystocktransaction.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystocktransaction.GroupTable,
			Columns: []string{entitystocktransaction.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystocktransaction.EntityTable,
			Columns: []string{entitystocktransaction.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystocktransaction.EntityTable,
			Columns: []string{entitystocktransaction.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitystocktransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntityStockTransactionUpdateOne is the builder for updating a single EntityStockTransaction entity.
type EntityStockTransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntityStockTransactionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntityStockTransactionUpdateOne) SetUpdatedAt(v time.Time) *EntityStockTransactionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *EntityStockTransactionUpdateOne) SetGroupID(v uuid.UUID) *EntityStockTransactionUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *EntityStockTransactionUpdateOne) SetNillableGroupID(v *uuid.UUID) *EntityStockTransactionUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *EntityStockTransactionUpdateOne) SetEntityID(v uuid.UUID) *EntityStockTransactionUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *EntityStockTransactionUpdateOne) SetNillableEntityID(v *uuid.UUID) *EntityStockTransactionUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *EntityStockTransactionUpdateOne) SetGroup(v *Group) *EntityStockTransactionUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_u *EntityStockTransactionUpdateOne) SetEntity(v *Entity) *EntityStockTransactionUpdateOne {
	return _u.SetEntityID(v.ID)
}

// Mutation returns the EntityStockTransactionMutation object of the builder.
func (_u *EntityStockTransactionUpdateOne) Mutation() *EntityStockTransactionMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *EntityStockTransactionUpdateOne) ClearGroup() *EntityStockTransactionUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearEntity clears the "entity" edge to the Entity entity.
func (_u *EntityStockTransactionUpdateOne) ClearEntity() *EntityStockTransactionUpdateOne {
	_u.mutation.ClearEntity()
	return _u
}

// Where appends a list predicates to the EntityStockTransactionUpdate builder.
func (_u *EntityStockTransactionUpdateOne) Where(ps ...predicate.EntityStockTransaction) *EntityStockTransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntityStockTransactionUpdateOne) Select(field string, fields ...string) *EntityStockTransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EntityStockTransaction entity.
func (_u *EntityStockTransactionUpdateOne) Save(ctx context.Context) (*EntityStockTransaction, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityStockTransactionUpdateOne) SaveX(ctx context.Context) *EntityStockTransaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntityStockTransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityStockTransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntityStockTransactionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entitystocktransaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityStockTransactionUpdateOne) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityStockTransaction.group"`)
	}
	if _u.mutation.EntityCleared() && len(_u.mutation.EntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityStockTransaction.entity"`)
	}
	return nil
}

func (_u *EntityStockTransactionUpdateOne) sqlSave(ctx context.Context) (_node *EntityStockTransaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entitystocktransaction.Table, entitystocktransaction.Columns, sqlgraph.NewFieldSpec(entitystocktransaction.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EntityStockTransaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entitystocktransaction.FieldID)
		for _, f := range fields {
			if !entitystocktransaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entitystocktransaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entitystocktransaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActorIDCleared() {
		_spec.ClearField(entitystocktransaction.FieldActorID, field.TypeUUID)
	}
	if _u.mutation.WorkflowCleared() {
		_spec.ClearField(entitystocktransaction.FieldWorkflow, field.TypeString)
	}
	if _u.mutation.SourceLocationIDCleared() {
		_spec.ClearField(entitystocktransaction.FieldSourceLocationID, field.TypeUUID)
	}
	if _u.mutation.DestinationLocationIDCleared() {
		_spec.ClearField(entitystocktransaction.FieldDestinationLocationID, field.TypeUUID)
	}
	if _u.mutation.SourceBeforeCleared() {
		_spec.ClearField(entitystocktransaction.FieldSourceBefore, field.TypeFloat64)
	}
	if _u.mutation.SourceAfterCleared() {
		_spec.ClearField(entitystocktransaction.FieldSourceAfter, field.TypeFloat64)
	}
	if _u.mutation.DestinationBeforeCleared() {
		_spec.ClearField(entitystocktransaction.FieldDestinationBefore, field.TypeFloat64)
	}
	if _u.mutation.DestinationAfterCleared() {
		_spec.ClearField(entitystocktransaction.FieldDestinationAfter, field.TypeFloat64)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(entitystocktransaction.FieldReason, field.TypeString)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystocktransaction.GroupTable,
			Columns: []string{entitystocktransaction.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystocktransaction.GroupTable,
			Columns: []string{entitystocktransaction.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystocktransaction.EntityTable,
			Columns: []string{entitystocktransaction.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystocktransaction.EntityTable,
			Columns: []string{entitystocktransaction.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EntityStockTransaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entitystocktransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
