// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entitystocktransaction"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// EntityStockTransactionDelete is the builder for deleting a EntityStockTransaction entity.
type EntityStockTransactionDelete struct {
	config
	hooks    []Hook
	mutation *EntityStockTransactionMutation
}

// Where appends a list predicates to the EntityStockTransactionDelete builder.
func (_d *EntityStockTransactionDelete) Where(ps ...predicate.EntityStockTransaction) *EntityStockTransactionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EntityStockTransactionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EntityStockTransactionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EntityStockTransactionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(entitystocktransaction.Table, sqlgraph.NewFieldSpec(entitystocktransaction.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EntityStockTransactionDeleteOne is the builder for deleting a single EntityStockTransaction entity.
type EntityStockTransactionDeleteOne struct {
	_d *EntityStockTransactionDelete
}

// Where appends a list predicates to the EntityStockTransactionDelete builder.
func (_d *EntityStockTransactionDeleteOne) Where(ps ...predicate.EntityStockTransaction) *EntityStockTransactionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EntityStockTransactionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{entitystocktransaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EntityStockTransactionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
