// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entitystockallocation"
)

// EntityStockAllocationCreate is the builder for creating a EntityStockAllocation entity.
type EntityStockAllocationCreate struct {
	config
	mutation *EntityStockAllocationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *EntityStockAllocationCreate) SetCreatedAt(v time.Time) *EntityStockAllocationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EntityStockAllocationCreate) SetNillableCreatedAt(v *time.Time) *EntityStockAllocationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EntityStockAllocationCreate) SetUpdatedAt(v time.Time) *EntityStockAllocationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EntityStockAllocationCreate) SetNillableUpdatedAt(v *time.Time) *EntityStockAllocationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEntityID sets the "entity_id" field.
func (_c *EntityStockAllocationCreate) SetEntityID(v uuid.UUID) *EntityStockAllocationCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetLocationID sets the "location_id" field.
func (_c *EntityStockAllocationCreate) SetLocationID(v uuid.UUID) *EntityStockAllocationCreate {
	_c.mutation.SetLocationID(v)
	return _c
}

// SetNillableLocationID sets the "location_id" field if the given value is not nil.
func (_c *EntityStockAllocationCreate) SetNillableLocationID(v *uuid.UUID) *EntityStockAllocationCreate {
	if v != nil {
		_c.SetLocationID(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *EntityStockAllocationCreate) SetQuantity(v float64) *EntityStockAllocationCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *EntityStockAllocationCreate) SetIsDefault(v bool) *EntityStockAllocationCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *EntityStockAllocationCreate) SetNillableIsDefault(v *bool) *EntityStockAllocationCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EntityStockAllocationCreate) SetID(v uuid.UUID) *EntityStockAllocationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EntityStockAllocationCreate) SetNillableID(v *uuid.UUID) *EntityStockAllocationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_c *EntityStockAllocationCreate) SetEntity(v *Entity) *EntityStockAllocationCreate {
	return _c.SetEntityID(v.ID)
}

// SetLocation sets the "location" edge to the Entity entity.
func (_c *EntityStockAllocationCreate) SetLocation(v *Entity) *EntityStockAllocationCreate {
	return _c.SetLocationID(v.ID)
}

// Mutation returns the EntityStockAllocationMutation object of the builder.
func (_c *EntityStockAllocationCreate) Mutation() *EntityStockAllocationMutation {
	return _c.mutation
}

// Save creates the EntityStockAllocation in the database.
func (_c *EntityStockAllocationCreate) Save(ctx context.Context) (*EntityStockAllocation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntityStockAllocationCreate) SaveX(ctx context.Context) *EntityStockAllocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityStockAllocationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityStockAllocationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EntityStockAllocationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := entitystockallocation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := entitystockallocation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := entitystockallocation.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := entitystockallocation.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntityStockAllocationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EntityStockAllocation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EntityStockAllocation.updated_at"`)}
	}
	if _, ok := _c.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "EntityStockAllocation.entity_id"`)}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "EntityStockAllocation.quantity"`)}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "EntityStockAllocation.is_default"`)}
	}
	if len(_c.mutation.EntityIDs()) == 0 {
		return &ValidationError{Name: "entity", err: errors.New(`ent: missing required edge "EntityStockAllocation.entity"`)}
	}
	return nil
}

func (_c *EntityStockAllocationCreate) sqlSave(ctx context.Context) (*EntityStockAllocation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntityStockAllocationCreate) createSpec() (*EntityStockAllocation, *sqlgraph.CreateSpec) {
	var (
		_node = &EntityStockAllocation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entitystockallocation.Table, sqlgraph.NewFieldSpec(entitystockallocation.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(entitystockallocation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(entitystockallocation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(entitystockallocation.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(entitystockallocation.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if nodes := _c.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystockallocation.EntityTable,
			Columns: []string{entitystockallocation.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EntityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entitystockallocation.LocationTable,
			Columns: []string{entitystockallocation.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LocationID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EntityStockAllocationCreateBulk is the builder for creating many EntityStockAllocation entities in bulk.
type EntityStockAllocationCreateBulk struct {
	config
	err      error
	builders []*EntityStockAllocationCreate
}

// Save creates the EntityStockAllocation entities in the database.
func (_c *EntityStockAllocationCreateBulk) Save(ctx context.Context) ([]*EntityStockAllocation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EntityStockAllocation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntityStockAllocationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntityStockAllocationCreateBulk) SaveX(ctx context.Context) []*EntityStockAllocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityStockAllocationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityStockAllocationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
