// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayout"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayoutelement"
)

// LocationLayoutCreate is the builder for creating a LocationLayout entity.
type LocationLayoutCreate struct {
	config
	mutation *LocationLayoutMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *LocationLayoutCreate) SetCreatedAt(v time.Time) *LocationLayoutCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LocationLayoutCreate) SetNillableCreatedAt(v *time.Time) *LocationLayoutCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LocationLayoutCreate) SetUpdatedAt(v time.Time) *LocationLayoutCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LocationLayoutCreate) SetNillableUpdatedAt(v *time.Time) *LocationLayoutCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCanvasWidth sets the "canvas_width" field.
func (_c *LocationLayoutCreate) SetCanvasWidth(v int) *LocationLayoutCreate {
	_c.mutation.SetCanvasWidth(v)
	return _c
}

// SetNillableCanvasWidth sets the "canvas_width" field if the given value is not nil.
func (_c *LocationLayoutCreate) SetNillableCanvasWidth(v *int) *LocationLayoutCreate {
	if v != nil {
		_c.SetCanvasWidth(*v)
	}
	return _c
}

// SetCanvasHeight sets the "canvas_height" field.
func (_c *LocationLayoutCreate) SetCanvasHeight(v int) *LocationLayoutCreate {
	_c.mutation.SetCanvasHeight(v)
	return _c
}

// SetNillableCanvasHeight sets the "canvas_height" field if the given value is not nil.
func (_c *LocationLayoutCreate) SetNillableCanvasHeight(v *int) *LocationLayoutCreate {
	if v != nil {
		_c.SetCanvasHeight(*v)
	}
	return _c
}

// SetRevision sets the "revision" field.
func (_c *LocationLayoutCreate) SetRevision(v int) *LocationLayoutCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *LocationLayoutCreate) SetNillableRevision(v *int) *LocationLayoutCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LocationLayoutCreate) SetID(v uuid.UUID) *LocationLayoutCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LocationLayoutCreate) SetNillableID(v *uuid.UUID) *LocationLayoutCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the Entity entity by ID.
func (_c *LocationLayoutCreate) SetOwnerID(id uuid.UUID) *LocationLayoutCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the Entity entity.
func (_c *LocationLayoutCreate) SetOwner(v *Entity) *LocationLayoutCreate {
	return _c.SetOwnerID(v.ID)
}

// AddElementIDs adds the "elements" edge to the LocationLayoutElement entity by IDs.
func (_c *LocationLayoutCreate) AddElementIDs(ids ...uuid.UUID) *LocationLayoutCreate {
	_c.mutation.AddElementIDs(ids...)
	return _c
}

// AddElements adds the "elements" edges to the LocationLayoutElement entity.
func (_c *LocationLayoutCreate) AddElements(v ...*LocationLayoutElement) *LocationLayoutCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddElementIDs(ids...)
}

// Mutation returns the LocationLayoutMutation object of the builder.
func (_c *LocationLayoutCreate) Mutation() *LocationLayoutMutation {
	return _c.mutation
}

// Save creates the LocationLayout in the database.
func (_c *LocationLayoutCreate) Save(ctx context.Context) (*LocationLayout, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LocationLayoutCreate) SaveX(ctx context.Context) *LocationLayout {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LocationLayoutCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LocationLayoutCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LocationLayoutCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := locationlayout.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := locationlayout.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CanvasWidth(); !ok {
		v := locationlayout.DefaultCanvasWidth
		_c.mutation.SetCanvasWidth(v)
	}
	if _, ok := _c.mutation.CanvasHeight(); !ok {
		v := locationlayout.DefaultCanvasHeight
		_c.mutation.SetCanvasHeight(v)
	}
	if _, ok := _c.mutation.Revision(); !ok {
		v := locationlayout.DefaultRevision
		_c.mutation.SetRevision(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := locationlayout.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LocationLayoutCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LocationLayout.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LocationLayout.updated_at"`)}
	}
	if _, ok := _c.mutation.CanvasWidth(); !ok {
		return &ValidationError{Name: "canvas_width", err: errors.New(`ent: missing required field "LocationLayout.canvas_width"`)}
	}
	if v, ok := _c.mutation.CanvasWidth(); ok {
		if err := locationlayout.CanvasWidthValidator(v); err != nil {
			return &ValidationError{Name: "canvas_width", err: fmt.Errorf(`ent: validator failed for field "LocationLayout.canvas_width": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CanvasHeight(); !ok {
		return &ValidationError{Name: "canvas_height", err: errors.New(`ent: missing required field "LocationLayout.canvas_height"`)}
	}
	if v, ok := _c.mutation.CanvasHeight(); ok {
		if err := locationlayout.CanvasHeightValidator(v); err != nil {
			return &ValidationError{Name: "canvas_height", err: fmt.Errorf(`ent: validator failed for field "LocationLayout.canvas_height": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "LocationLayout.revision"`)}
	}
	if v, ok := _c.mutation.Revision(); ok {
		if err := locationlayout.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "LocationLayout.revision": %w`, err)}
		}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "LocationLayout.owner"`)}
	}
	return nil
}

func (_c *LocationLayoutCreate) sqlSave(ctx context.Context) (*LocationLayout, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LocationLayoutCreate) createSpec() (*LocationLayout, *sqlgraph.CreateSpec) {
	var (
		_node = &LocationLayout{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(locationlayout.Table, sqlgraph.NewFieldSpec(locationlayout.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(locationlayout.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(locationlayout.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CanvasWidth(); ok {
		_spec.SetField(locationlayout.FieldCanvasWidth, field.TypeInt, value)
		_node.CanvasWidth = value
	}
	if value, ok := _c.mutation.CanvasHeight(); ok {
		_spec.SetField(locationlayout.FieldCanvasHeight, field.TypeInt, value)
		_node.CanvasHeight = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(locationlayout.FieldRevision, field.TypeInt, value)
		_node.Revision = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   locationlayout.OwnerTable,
			Columns: []string{locationlayout.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.entity_location_layout = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ElementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   locationlayout.ElementsTable,
			Columns: []string{locationlayout.ElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationlayoutelement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LocationLayoutCreateBulk is the builder for creating many LocationLayout entities in bulk.
type LocationLayoutCreateBulk struct {
	config
	err      error
	builders []*LocationLayoutCreate
}

// Save creates the LocationLayout entities in the database.
func (_c *LocationLayoutCreateBulk) Save(ctx context.Context) ([]*LocationLayout, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LocationLayout, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LocationLayoutMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LocationLayoutCreateBulk) SaveX(ctx context.Context) []*LocationLayout {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LocationLayoutCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LocationLayoutCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
