// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayout"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayoutelement"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// LocationLayoutUpdate is the builder for updating LocationLayout entities.
type LocationLayoutUpdate struct {
	config
	hooks    []Hook
	mutation *LocationLayoutMutation
}

// Where appends a list predicates to the LocationLayoutUpdate builder.
func (_u *LocationLayoutUpdate) Where(ps ...predicate.LocationLayout) *LocationLayoutUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LocationLayoutUpdate) SetUpdatedAt(v time.Time) *LocationLayoutUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCanvasWidth sets the "canvas_width" field.
func (_u *LocationLayoutUpdate) SetCanvasWidth(v int) *LocationLayoutUpdate {
	_u.mutation.ResetCanvasWidth()
	_u.mutation.SetCanvasWidth(v)
	return _u
}

// SetNillableCanvasWidth sets the "canvas_width" field if the given value is not nil.
func (_u *LocationLayoutUpdate) SetNillableCanvasWidth(v *int) *LocationLayoutUpdate {
	if v != nil {
		_u.SetCanvasWidth(*v)
	}
	return _u
}

// AddCanvasWidth adds value to the "canvas_width" field.
func (_u *LocationLayoutUpdate) AddCanvasWidth(v int) *LocationLayoutUpdate {
	_u.mutation.AddCanvasWidth(v)
	return _u
}

// SetCanvasHeight sets the "canvas_height" field.
func (_u *LocationLayoutUpdate) SetCanvasHeight(v int) *LocationLayoutUpdate {
	_u.mutation.ResetCanvasHeight()
	_u.mutation.SetCanvasHeight(v)
	return _u
}

// SetNillableCanvasHeight sets the "canvas_height" field if the given value is not nil.
func (_u *LocationLayoutUpdate) SetNillableCanvasHeight(v *int) *LocationLayoutUpdate {
	if v != nil {
		_u.SetCanvasHeight(*v)
	}
	return _u
}

// AddCanvasHeight adds value to the "canvas_height" field.
func (_u *LocationLayoutUpdate) AddCanvasHeight(v int) *LocationLayoutUpdate {
	_u.mutation.AddCanvasHeight(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *LocationLayoutUpdate) SetRevision(v int) *LocationLayoutUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *LocationLayoutUpdate) SetNillableRevision(v *int) *LocationLayoutUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *LocationLayoutUpdate) AddRevision(v int) *LocationLayoutUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the Entity entity by ID.
func (_u *LocationLayoutUpdate) SetOwnerID(id uuid.UUID) *LocationLayoutUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the Entity entity.
func (_u *LocationLayoutUpdate) SetOwner(v *Entity) *LocationLayoutUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddElementIDs adds the "elements" edge to the LocationLayoutElement entity by IDs.
func (_u *LocationLayoutUpdate) AddElementIDs(ids ...uuid.UUID) *LocationLayoutUpdate {
	_u.mutation.AddElementIDs(ids...)
	return _u
}

// AddElements adds the "elements" edges to the LocationLayoutElement entity.
func (_u *LocationLayoutUpdate) AddElements(v ...*LocationLayoutElement) *LocationLayoutUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddElementIDs(ids...)
}

// Mutation returns the LocationLayoutMutation object of the builder.
func (_u *LocationLayoutUpdate) Mutation() *LocationLayoutMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the Entity entity.
func (_u *LocationLayoutUpdate) ClearOwner() *LocationLayoutUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearElements clears all "elements" edges to the LocationLayoutElement entity.
func (_u *LocationLayoutUpdate) ClearElements() *LocationLayoutUpdate {
	_u.mutation.ClearElements()
	return _u
}

// RemoveElementIDs removes the "elements" edge to LocationLayoutElement entities by IDs.
func (_u *LocationLayoutUpdate) RemoveElementIDs(ids ...uuid.UUID) *LocationLayoutUpdate {
	_u.mutation.RemoveElementIDs(ids...)
	return _u
}

// RemoveElements removes "elements" edges to LocationLayoutElement entities.
func (_u *LocationLayoutUpdate) RemoveElements(v ...*LocationLayoutElement) *LocationLayoutUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveElementIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LocationLayoutUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LocationLayoutUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LocationLayoutUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LocationLayoutUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LocationLayoutUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := locationlayout.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LocationLayoutUpdate) check() error {
	if v, ok := _u.mutation.CanvasWidth(); ok {
		if err := locationlayout.CanvasWidthValidator(v); err != nil {
			return &ValidationError{Name: "canvas_width", err: fmt.Errorf(`ent: validator failed for field "LocationLayout.canvas_width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CanvasHeight(); ok {
		if err := locationlayout.CanvasHeightValidator(v); err != nil {
			return &ValidationError{Name: "canvas_height", err: fmt.Errorf(`ent: validator failed for field "LocationLayout.canvas_height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := locationlayout.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "LocationLayout.revision": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LocationLayout.owner"`)
	}
	return nil
}

func (_u *LocationLayoutUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(locationlayout.Table, locationlayout.Columns, sqlgraph.NewFieldSpec(locationlayout.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(locationlayout.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CanvasWidth(); ok {
		_spec.SetField(locationlayout.FieldCanvasWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCanvasWidth(); ok {
		_spec.AddField(locationlayout.FieldCanvasWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CanvasHeight(); ok {
		_spec.SetField(locationlayout.FieldCanvasHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCanvasHeight(); ok {
		_spec.AddField(locationlayout.FieldCanvasHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(locationlayout.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(locationlayout.FieldRevision, field.TypeInt, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   locationlayout.OwnerTable,
			Columns: []string{locationlayout.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   locationlayout.OwnerTable,
			Columns: []string{locationlayout.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ElementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   locationlayout.ElementsTable,
			Columns: []string{locationlayout.ElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationlayoutelement.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedElementsIDs(); len(nodes) > 0 && !_u.mutation.ElementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   locationlayout.ElementsTable,
			Columns: []string{locationlayout.ElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationlayoutelement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ElementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   locationlayout.ElementsTable,
			Columns: []string{locationlayout.ElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationlayoutelement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{locationlayout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LocationLayoutUpdateOne is the builder for updating a single LocationLayout entity.
type LocationLayoutUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LocationLayoutMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LocationLayoutUpdateOne) SetUpdatedAt(v time.Time) *LocationLayoutUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCanvasWidth sets the "canvas_width" field.
func (_u *LocationLayoutUpdateOne) SetCanvasWidth(v int) *LocationLayoutUpdateOne {
	_u.mutation.ResetCanvasWidth()
	_u.mutation.SetCanvasWidth(v)
	return _u
}

// SetNillableCanvasWidth sets the "canvas_width" field if the given value is not nil.
func (_u *LocationLayoutUpdateOne) SetNillableCanvasWidth(v *int) *LocationLayoutUpdateOne {
	if v != nil {
		_u.SetCanvasWidth(*v)
	}
	return _u
}

// AddCanvasWidth adds value to the "canvas_width" field.
func (_u *LocationLayoutUpdateOne) AddCanvasWidth(v int) *LocationLayoutUpdateOne {
	_u.mutation.AddCanvasWidth(v)
	return _u
}

// SetCanvasHeight sets the "canvas_height" field.
func (_u *LocationLayoutUpdateOne) SetCanvasHeight(v int) *LocationLayoutUpdateOne {
	_u.mutation.ResetCanvasHeight()
	_u.mutation.SetCanvasHeight(v)
	return _u
}

// SetNillableCanvasHeight sets the "canvas_height" field if the given value is not nil.
func (_u *LocationLayoutUpdateOne) SetNillableCanvasHeight(v *int) *LocationLayoutUpdateOne {
	if v != nil {
		_u.SetCanvasHeight(*v)
	}
	return _u
}

// AddCanvasHeight adds value to the "canvas_height" field.
func (_u *LocationLayoutUpdateOne) AddCanvasHeight(v int) *LocationLayoutUpdateOne {
	_u.mutation.AddCanvasHeight(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *LocationLayoutUpdateOne) SetRevision(v int) *LocationLayoutUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *LocationLayoutUpdateOne) SetNillableRevision(v *int) *LocationLayoutUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *LocationLayoutUpdateOne) AddRevision(v int) *LocationLayoutUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the Entity entity by ID.
func (_u *LocationLayoutUpdateOne) SetOwnerID(id uuid.UUID) *LocationLayoutUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the Entity entity.
func (_u *LocationLayoutUpdateOne) SetOwner(v *Entity) *LocationLayoutUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddElementIDs adds the "elements" edge to the LocationLayoutElement entity by IDs.
func (_u *LocationLayoutUpdateOne) AddElementIDs(ids ...uuid.UUID) *LocationLayoutUpdateOne {
	_u.mutation.AddElementIDs(ids...)
	return _u
}

// AddElements adds the "elements" edges to the LocationLayoutElement entity.
func (_u *LocationLayoutUpdateOne) AddElements(v ...*LocationLayoutElement) *LocationLayoutUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddElementIDs(ids...)
}

// Mutation returns the LocationLayoutMutation object of the builder.
func (_u *LocationLayoutUpdateOne) Mutation() *LocationLayoutMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the Entity entity.
func (_u *LocationLayoutUpdateOne) ClearOwner() *LocationLayoutUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearElements clears all "elements" edges to the LocationLayoutElement entity.
func (_u *LocationLayoutUpdateOne) ClearElements() *LocationLayoutUpdateOne {
	_u.mutation.ClearElements()
	return _u
}

// RemoveElementIDs removes the "elements" edge to LocationLayoutElement entities by IDs.
func (_u *LocationLayoutUpdateOne) RemoveElementIDs(ids ...uuid.UUID) *LocationLayoutUpdateOne {
	_u.mutation.RemoveElementIDs(ids...)
	return _u
}

// RemoveElements removes "elements" edges to LocationLayoutElement entities.
func (_u *LocationLayoutUpdateOne) RemoveElements(v ...*LocationLayoutElement) *LocationLayoutUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveElementIDs(ids...)
}

// Where appends a list predicates to the LocationLayoutUpdate builder.
func (_u *LocationLayoutUpdateOne) Where(ps ...predicate.LocationLayout) *LocationLayoutUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LocationLayoutUpdateOne) Select(field string, fields ...string) *LocationLayoutUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LocationLayout entity.
func (_u *LocationLayoutUpdateOne) Save(ctx context.Context) (*LocationLayout, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LocationLayoutUpdateOne) SaveX(ctx context.Context) *LocationLayout {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LocationLayoutUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LocationLayoutUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LocationLayoutUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := locationlayout.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LocationLayoutUpdateOne) check() error {
	if v, ok := _u.mutation.CanvasWidth(); ok {
		if err := locationlayout.CanvasWidthValidator(v); err != nil {
			return &ValidationError{Name: "canvas_width", err: fmt.Errorf(`ent: validator failed for field "LocationLayout.canvas_width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CanvasHeight(); ok {
		if err := locationlayout.CanvasHeightValidator(v); err != nil {
			return &ValidationError{Name: "canvas_height", err: fmt.Errorf(`ent: validator failed for field "LocationLayout.canvas_height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := locationlayout.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "LocationLayout.revision": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LocationLayout.owner"`)
	}
	return nil
}

func (_u *LocationLayoutUpdateOne) sqlSave(ctx context.Context) (_node *LocationLayout, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(locationlayout.Table, locationlayout.Columns, sqlgraph.NewFieldSpec(locationlayout.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LocationLayout.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, locationlayout.FieldID)
		for _, f := range fields {
			if !locationlayout.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != locationlayout.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(locationlayout.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CanvasWidth(); ok {
		_spec.SetField(locationlayout.FieldCanvasWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCanvasWidth(); ok {
		_spec.AddField(locationlayout.FieldCanvasWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CanvasHeight(); ok {
		_spec.SetField(locationlayout.FieldCanvasHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCanvasHeight(); ok {
		_spec.AddField(locationlayout.FieldCanvasHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(locationlayout.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(locationlayout.FieldRevision, field.TypeInt, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   locationlayout.OwnerTable,
			Columns: []string{locationlayout.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   locationlayout.OwnerTable,
			Columns: []string{locationlayout.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ElementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   locationlayout.ElementsTable,
			Columns: []string{locationlayout.ElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationlayoutelement.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedElementsIDs(); len(nodes) > 0 && !_u.mutation.ElementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   locationlayout.ElementsTable,
			Columns: []string{locationlayout.ElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationlayoutelement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ElementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   locationlayout.ElementsTable,
			Columns: []string{locationlayout.ElementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationlayoutelement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LocationLayout{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{locationlayout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
