// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayout"
)

// LocationLayout is the model entity for the LocationLayout schema.
type LocationLayout struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CanvasWidth holds the value of the "canvas_width" field.
	CanvasWidth int `json:"canvas_width,omitempty"`
	// CanvasHeight holds the value of the "canvas_height" field.
	CanvasHeight int `json:"canvas_height,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision int `json:"revision,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LocationLayoutQuery when eager-loading is set.
	Edges                  LocationLayoutEdges `json:"edges"`
	entity_location_layout *uuid.UUID
	selectValues           sql.SelectValues
}

// LocationLayoutEdges holds the relations/edges for other nodes in the graph.
type LocationLayoutEdges struct {
	// Owner holds the value of the owner edge.
	Owner *Entity `json:"owner,omitempty"`
	// Elements holds the value of the elements edge.
	Elements []*LocationLayoutElement `json:"elements,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LocationLayoutEdges) OwnerOrErr() (*Entity, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: entity.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// ElementsOrErr returns the Elements value or an error if the edge
// was not loaded in eager-loading.
func (e LocationLayoutEdges) ElementsOrErr() ([]*LocationLayoutElement, error) {
	if e.loadedTypes[1] {
		return e.Elements, nil
	}
	return nil, &NotLoadedError{edge: "elements"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LocationLayout) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case locationlayout.FieldCanvasWidth, locationlayout.FieldCanvasHeight, locationlayout.FieldRevision:
			values[i] = new(sql.NullInt64)
		case locationlayout.FieldCreatedAt, locationlayout.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case locationlayout.FieldID:
			values[i] = new(uuid.UUID)
		case locationlayout.ForeignKeys[0]: // entity_location_layout
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LocationLayout fields.
func (_m *LocationLayout) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case locationlayout.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case locationlayout.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case locationlayout.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case locationlayout.FieldCanvasWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field canvas_width", values[i])
			} else if value.Valid {
				_m.CanvasWidth = int(value.Int64)
			}
		case locationlayout.FieldCanvasHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field canvas_height", values[i])
			} else if value.Valid {
				_m.CanvasHeight = int(value.Int64)
			}
		case locationlayout.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = int(value.Int64)
			}
		case locationlayout.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field entity_location_layout", values[i])
			} else if value.Valid {
				_m.entity_location_layout = new(uuid.UUID)
				*_m.entity_location_layout = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LocationLayout.
// This includes values selected through modifiers, order, etc.
func (_m *LocationLayout) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the LocationLayout entity.
func (_m *LocationLayout) QueryOwner() *EntityQuery {
	return NewLocationLayoutClient(_m.config).QueryOwner(_m)
}

// QueryElements queries the "elements" edge of the LocationLayout entity.
func (_m *LocationLayout) QueryElements() *LocationLayoutElementQuery {
	return NewLocationLayoutClient(_m.config).QueryElements(_m)
}

// Update returns a builder for updating this LocationLayout.
// Note that you need to call LocationLayout.Unwrap() before calling this method if this LocationLayout
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LocationLayout) Update() *LocationLayoutUpdateOne {
	return NewLocationLayoutClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LocationLayout entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LocationLayout) Unwrap() *LocationLayout {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LocationLayout is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LocationLayout) String() string {
	var builder strings.Builder
	builder.WriteString("LocationLayout(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("canvas_width=")
	builder.WriteString(fmt.Sprintf("%v", _m.CanvasWidth))
	builder.WriteString(", ")
	builder.WriteString("canvas_height=")
	builder.WriteString(fmt.Sprintf("%v", _m.CanvasHeight))
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteByte(')')
	return builder.String()
}

// LocationLayouts is a parsable slice of LocationLayout.
type LocationLayouts []*LocationLayout
