// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayout"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayoutelement"
)

// LocationLayoutElementCreate is the builder for creating a LocationLayoutElement entity.
type LocationLayoutElementCreate struct {
	config
	mutation *LocationLayoutElementMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *LocationLayoutElementCreate) SetCreatedAt(v time.Time) *LocationLayoutElementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LocationLayoutElementCreate) SetNillableCreatedAt(v *time.Time) *LocationLayoutElementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LocationLayoutElementCreate) SetUpdatedAt(v time.Time) *LocationLayoutElementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LocationLayoutElementCreate) SetNillableUpdatedAt(v *time.Time) *LocationLayoutElementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *LocationLayoutElementCreate) SetKind(v locationlayoutelement.Kind) *LocationLayoutElementCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetX sets the "x" field.
func (_c *LocationLayoutElementCreate) SetX(v float64) *LocationLayoutElementCreate {
	_c.mutation.SetX(v)
	return _c
}

// SetY sets the "y" field.
func (_c *LocationLayoutElementCreate) SetY(v float64) *LocationLayoutElementCreate {
	_c.mutation.SetY(v)
	return _c
}

// SetWidth sets the "width" field.
func (_c *LocationLayoutElementCreate) SetWidth(v float64) *LocationLayoutElementCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *LocationLayoutElementCreate) SetNillableWidth(v *float64) *LocationLayoutElementCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *LocationLayoutElementCreate) SetHeight(v float64) *LocationLayoutElementCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *LocationLayoutElementCreate) SetNillableHeight(v *float64) *LocationLayoutElementCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetEndX sets the "end_x" field.
func (_c *LocationLayoutElementCreate) SetEndX(v float64) *LocationLayoutElementCreate {
	_c.mutation.SetEndX(v)
	return _c
}

// SetNillableEndX sets the "end_x" field if the given value is not nil.
func (_c *LocationLayoutElementCreate) SetNillableEndX(v *float64) *LocationLayoutElementCreate {
	if v != nil {
		_c.SetEndX(*v)
	}
	return _c
}

// SetEndY sets the "end_y" field.
func (_c *LocationLayoutElementCreate) SetEndY(v float64) *LocationLayoutElementCreate {
	_c.mutation.SetEndY(v)
	return _c
}

// SetNillableEndY sets the "end_y" field if the given value is not nil.
func (_c *LocationLayoutElementCreate) SetNillableEndY(v *float64) *LocationLayoutElementCreate {
	if v != nil {
		_c.SetEndY(*v)
	}
	return _c
}

// SetRotation sets the "rotation" field.
func (_c *LocationLayoutElementCreate) SetRotation(v float64) *LocationLayoutElementCreate {
	_c.mutation.SetRotation(v)
	return _c
}

// SetNillableRotation sets the "rotation" field if the given value is not nil.
func (_c *LocationLayoutElementCreate) SetNillableRotation(v *float64) *LocationLayoutElementCreate {
	if v != nil {
		_c.SetRotation(*v)
	}
	return _c
}

// SetZOrder sets the "z_order" field.
func (_c *LocationLayoutElementCreate) SetZOrder(v int) *LocationLayoutElementCreate {
	_c.mutation.SetZOrder(v)
	return _c
}

// SetNillableZOrder sets the "z_order" field if the given value is not nil.
func (_c *LocationLayoutElementCreate) SetNillableZOrder(v *int) *LocationLayoutElementCreate {
	if v != nil {
		_c.SetZOrder(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LocationLayoutElementCreate) SetID(v uuid.UUID) *LocationLayoutElementCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LocationLayoutElementCreate) SetNillableID(v *uuid.UUID) *LocationLayoutElementCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetLayoutID sets the "layout" edge to the LocationLayout entity by ID.
func (_c *LocationLayoutElementCreate) SetLayoutID(id uuid.UUID) *LocationLayoutElementCreate {
	_c.mutation.SetLayoutID(id)
	return _c
}

// SetLayout sets the "layout" edge to the LocationLayout entity.
func (_c *LocationLayoutElementCreate) SetLayout(v *LocationLayout) *LocationLayoutElementCreate {
	return _c.SetLayoutID(v.ID)
}

// SetTargetID sets the "target" edge to the Entity entity by ID.
func (_c *LocationLayoutElementCreate) SetTargetID(id uuid.UUID) *LocationLayoutElementCreate {
	_c.mutation.SetTargetID(id)
	return _c
}

// SetNillableTargetID sets the "target" edge to the Entity entity by ID if the given value is not nil.
func (_c *LocationLayoutElementCreate) SetNillableTargetID(id *uuid.UUID) *LocationLayoutElementCreate {
	if id != nil {
		_c = _c.SetTargetID(*id)
	}
	return _c
}

// SetTarget sets the "target" edge to the Entity entity.
func (_c *LocationLayoutElementCreate) SetTarget(v *Entity) *LocationLayoutElementCreate {
	return _c.SetTargetID(v.ID)
}

// Mutation returns the LocationLayoutElementMutation object of the builder.
func (_c *LocationLayoutElementCreate) Mutation() *LocationLayoutElementMutation {
	return _c.mutation
}

// Save creates the LocationLayoutElement in the database.
func (_c *LocationLayoutElementCreate) Save(ctx context.Context) (*LocationLayoutElement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LocationLayoutElementCreate) SaveX(ctx context.Context) *LocationLayoutElement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LocationLayoutElementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LocationLayoutElementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LocationLayoutElementCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := locationlayoutelement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := locationlayoutelement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Width(); !ok {
		v := locationlayoutelement.DefaultWidth
		_c.mutation.SetWidth(v)
	}
	if _, ok := _c.mutation.Height(); !ok {
		v := locationlayoutelement.DefaultHeight
		_c.mutation.SetHeight(v)
	}
	if _, ok := _c.mutation.EndX(); !ok {
		v := locationlayoutelement.DefaultEndX
		_c.mutation.SetEndX(v)
	}
	if _, ok := _c.mutation.EndY(); !ok {
		v := locationlayoutelement.DefaultEndY
		_c.mutation.SetEndY(v)
	}
	if _, ok := _c.mutation.Rotation(); !ok {
		v := locationlayoutelement.DefaultRotation
		_c.mutation.SetRotation(v)
	}
	if _, ok := _c.mutation.ZOrder(); !ok {
		v := locationlayoutelement.DefaultZOrder
		_c.mutation.SetZOrder(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := locationlayoutelement.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LocationLayoutElementCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LocationLayoutElement.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LocationLayoutElement.updated_at"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "LocationLayoutElement.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := locationlayoutelement.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "LocationLayoutElement.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.X(); !ok {
		return &ValidationError{Name: "x", err: errors.New(`ent: missing required field "LocationLayoutElement.x"`)}
	}
	if _, ok := _c.mutation.Y(); !ok {
		return &ValidationError{Name: "y", err: errors.New(`ent: missing required field "LocationLayoutElement.y"`)}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "LocationLayoutElement.width"`)}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "LocationLayoutElement.height"`)}
	}
	if _, ok := _c.mutation.EndX(); !ok {
		return &ValidationError{Name: "end_x", err: errors.New(`ent: missing required field "LocationLayoutElement.end_x"`)}
	}
	if _, ok := _c.mutation.EndY(); !ok {
		return &ValidationError{Name: "end_y", err: errors.New(`ent: missing required field "LocationLayoutElement.end_y"`)}
	}
	if _, ok := _c.mutation.Rotation(); !ok {
		return &ValidationError{Name: "rotation", err: errors.New(`ent: missing required field "LocationLayoutElement.rotation"`)}
	}
	if _, ok := _c.mutation.ZOrder(); !ok {
		return &ValidationError{Name: "z_order", err: errors.New(`ent: missing required field "LocationLayoutElement.z_order"`)}
	}
	if len(_c.mutation.LayoutIDs()) == 0 {
		return &ValidationError{Name: "layout", err: errors.New(`ent: missing required edge "LocationLayoutElement.layout"`)}
	}
	return nil
}

func (_c *LocationLayoutElementCreate) sqlSave(ctx context.Context) (*LocationLayoutElement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LocationLayoutElementCreate) createSpec() (*LocationLayoutElement, *sqlgraph.CreateSpec) {
	var (
		_node = &LocationLayoutElement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(locationlayoutelement.Table, sqlgraph.NewFieldSpec(locationlayoutelement.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(locationlayoutelement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(locationlayoutelement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(locationlayoutelement.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.X(); ok {
		_spec.SetField(locationlayoutelement.FieldX, field.TypeFloat64, value)
		_node.X = value
	}
	if value, ok := _c.mutation.Y(); ok {
		_spec.SetField(locationlayoutelement.FieldY, field.TypeFloat64, value)
		_node.Y = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(locationlayoutelement.FieldWidth, field.TypeFloat64, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(locationlayoutelement.FieldHeight, field.TypeFloat64, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.EndX(); ok {
		_spec.SetField(locationlayoutelement.FieldEndX, field.TypeFloat64, value)
		_node.EndX = value
	}
	if value, ok := _c.mutation.EndY(); ok {
		_spec.SetField(locationlayoutelement.FieldEndY, field.TypeFloat64, value)
		_node.EndY = value
	}
	if value, ok := _c.mutation.Rotation(); ok {
		_spec.SetField(locationlayoutelement.FieldRotation, field.TypeFloat64, value)
		_node.Rotation = value
	}
	if value, ok := _c.mutation.ZOrder(); ok {
		_spec.SetField(locationlayoutelement.FieldZOrder, field.TypeInt, value)
		_node.ZOrder = value
	}
	if nodes := _c.mutation.LayoutIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationlayoutelement.LayoutTable,
			Columns: []string{locationlayoutelement.LayoutColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationlayout.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.location_layout_elements = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationlayoutelement.TargetTable,
			Columns: []string{locationlayoutelement.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.entity_layout_placements = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LocationLayoutElementCreateBulk is the builder for creating many LocationLayoutElement entities in bulk.
type LocationLayoutElementCreateBulk struct {
	config
	err      error
	builders []*LocationLayoutElementCreate
}

// Save creates the LocationLayoutElement entities in the database.
func (_c *LocationLayoutElementCreateBulk) Save(ctx context.Context) ([]*LocationLayoutElement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LocationLayoutElement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LocationLayoutElementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LocationLayoutElementCreateBulk) SaveX(ctx context.Context) []*LocationLayoutElement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LocationLayoutElementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LocationLayoutElementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
