// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayout"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayoutelement"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// LocationLayoutQuery is the builder for querying LocationLayout entities.
type LocationLayoutQuery struct {
	config
	ctx          *QueryContext
	order        []locationlayout.OrderOption
	inters       []Interceptor
	predicates   []predicate.LocationLayout
	withOwner    *EntityQuery
	withElements *LocationLayoutElementQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LocationLayoutQuery builder.
func (_q *LocationLayoutQuery) Where(ps ...predicate.LocationLayout) *LocationLayoutQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *LocationLayoutQuery) Limit(limit int) *LocationLayoutQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *LocationLayoutQuery) Offset(offset int) *LocationLayoutQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *LocationLayoutQuery) Unique(unique bool) *LocationLayoutQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *LocationLayoutQuery) Order(o ...locationlayout.OrderOption) *LocationLayoutQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOwner chains the current query on the "owner" edge.
func (_q *LocationLayoutQuery) QueryOwner() *EntityQuery {
	query := (&EntityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(locationlayout.Table, locationlayout.FieldID, selector),
			sqlgraph.To(entity.Table, entity.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, locationlayout.OwnerTable, locationlayout.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryElements chains the current query on the "elements" edge.
func (_q *LocationLayoutQuery) QueryElements() *LocationLayoutElementQuery {
	query := (&LocationLayoutElementClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(locationlayout.Table, locationlayout.FieldID, selector),
			sqlgraph.To(locationlayoutelement.Table, locationlayoutelement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, locationlayout.ElementsTable, locationlayout.ElementsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LocationLayout entity from the query.
// Returns a *NotFoundError when no LocationLayout was found.
func (_q *LocationLayoutQuery) First(ctx context.Context) (*LocationLayout, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{locationlayout.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *LocationLayoutQuery) FirstX(ctx context.Context) *LocationLayout {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LocationLayout ID from the query.
// Returns a *NotFoundError when no LocationLayout ID was found.
func (_q *LocationLayoutQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{locationlayout.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *LocationLayoutQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LocationLayout entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LocationLayout entity is found.
// Returns a *NotFoundError when no LocationLayout entities are found.
func (_q *LocationLayoutQuery) Only(ctx context.Context) (*LocationLayout, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{locationlayout.Label}
	default:
		return nil, &NotSingularError{locationlayout.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *LocationLayoutQuery) OnlyX(ctx context.Context) *LocationLayout {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LocationLayout ID in the query.
// Returns a *NotSingularError when more than one LocationLayout ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *LocationLayoutQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{locationlayout.Label}
	default:
		err = &NotSingularError{locationlayout.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *LocationLayoutQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LocationLayouts.
func (_q *LocationLayoutQuery) All(ctx context.Context) ([]*LocationLayout, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LocationLayout, *LocationLayoutQuery]()
	return withInterceptors[[]*LocationLayout](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *LocationLayoutQuery) AllX(ctx context.Context) []*LocationLayout {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LocationLayout IDs.
func (_q *LocationLayoutQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(locationlayout.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *LocationLayoutQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *LocationLayoutQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*LocationLayoutQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *LocationLayoutQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *LocationLayoutQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *LocationLayoutQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LocationLayoutQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *LocationLayoutQuery) Clone() *LocationLayoutQuery {
	if _q == nil {
		return nil
	}
	return &LocationLayoutQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]locationlayout.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.LocationLayout{}, _q.predicates...),
		withOwner:    _q.withOwner.Clone(),
		withElements: _q.withElements.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LocationLayoutQuery) WithOwner(opts ...func(*EntityQuery)) *LocationLayoutQuery {
	query := (&EntityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOwner = query
	return _q
}

// WithElements tells the query-builder to eager-load the nodes that are connected to
// the "elements" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LocationLayoutQuery) WithElements(opts ...func(*LocationLayoutElementQuery)) *LocationLayoutQuery {
	query := (&LocationLayoutElementClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withElements = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LocationLayout.Query().
//		GroupBy(locationlayout.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *LocationLayoutQuery) GroupBy(field string, fields ...string) *LocationLayoutGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LocationLayoutGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = locationlayout.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.LocationLayout.Query().
//		Select(locationlayout.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *LocationLayoutQuery) Select(fields ...string) *LocationLayoutSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &LocationLayoutSelect{LocationLayoutQuery: _q}
	sbuild.label = locationlayout.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LocationLayoutSelect configured with the given aggregations.
func (_q *LocationLayoutQuery) Aggregate(fns ...AggregateFunc) *LocationLayoutSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *LocationLayoutQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !locationlayout.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *LocationLayoutQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LocationLayout, error) {
	var (
		nodes       = []*LocationLayout{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withOwner != nil,
			_q.withElements != nil,
		}
	)
	if _q.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, locationlayout.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LocationLayout).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LocationLayout{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOwner; query != nil {
		if err := _q.loadOwner(ctx, query, nodes, nil,
			func(n *LocationLayout, e *Entity) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withElements; query != nil {
		if err := _q.loadElements(ctx, query, nodes,
			func(n *LocationLayout) { n.Edges.Elements = []*LocationLayoutElement{} },
			func(n *LocationLayout, e *LocationLayoutElement) { n.Edges.Elements = append(n.Edges.Elements, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *LocationLayoutQuery) loadOwner(ctx context.Context, query *EntityQuery, nodes []*LocationLayout, init func(*LocationLayout), assign func(*LocationLayout, *Entity)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*LocationLayout)
	for i := range nodes {
		if nodes[i].entity_location_layout == nil {
			continue
		}
		fk := *nodes[i].entity_location_layout
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(entity.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "entity_location_layout" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *LocationLayoutQuery) loadElements(ctx context.Context, query *LocationLayoutElementQuery, nodes []*LocationLayout, init func(*LocationLayout), assign func(*LocationLayout, *LocationLayoutElement)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*LocationLayout)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.LocationLayoutElement(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(locationlayout.ElementsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.location_layout_elements
		if fk == nil {
			return fmt.Errorf(`foreign-key "location_layout_elements" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "location_layout_elements" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *LocationLayoutQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *LocationLayoutQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(locationlayout.Table, locationlayout.Columns, sqlgraph.NewFieldSpec(locationlayout.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, locationlayout.FieldID)
		for i := range fields {
			if fields[i] != locationlayout.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *LocationLayoutQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(locationlayout.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = locationlayout.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LocationLayoutGroupBy is the group-by builder for LocationLayout entities.
type LocationLayoutGroupBy struct {
	selector
	build *LocationLayoutQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *LocationLayoutGroupBy) Aggregate(fns ...AggregateFunc) *LocationLayoutGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *LocationLayoutGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LocationLayoutQuery, *LocationLayoutGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *LocationLayoutGroupBy) sqlScan(ctx context.Context, root *LocationLayoutQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LocationLayoutSelect is the builder for selecting fields of LocationLayout entities.
type LocationLayoutSelect struct {
	*LocationLayoutQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *LocationLayoutSelect) Aggregate(fns ...AggregateFunc) *LocationLayoutSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *LocationLayoutSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LocationLayoutQuery, *LocationLayoutSelect](ctx, _s.LocationLayoutQuery, _s, _s.inters, v)
}

func (_s *LocationLayoutSelect) sqlScan(ctx context.Context, root *LocationLayoutQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
