// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayout"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayoutelement"
)

// LocationLayoutElement is the model entity for the LocationLayoutElement schema.
type LocationLayoutElement struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind locationlayoutelement.Kind `json:"kind,omitempty"`
	// X holds the value of the "x" field.
	X float64 `json:"x,omitempty"`
	// Y holds the value of the "y" field.
	Y float64 `json:"y,omitempty"`
	// Width holds the value of the "width" field.
	Width float64 `json:"width,omitempty"`
	// Height holds the value of the "height" field.
	Height float64 `json:"height,omitempty"`
	// EndX holds the value of the "end_x" field.
	EndX float64 `json:"end_x,omitempty"`
	// EndY holds the value of the "end_y" field.
	EndY float64 `json:"end_y,omitempty"`
	// Rotation holds the value of the "rotation" field.
	Rotation float64 `json:"rotation,omitempty"`
	// ZOrder holds the value of the "z_order" field.
	ZOrder int `json:"z_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LocationLayoutElementQuery when eager-loading is set.
	Edges                    LocationLayoutElementEdges `json:"edges"`
	entity_layout_placements *uuid.UUID
	location_layout_elements *uuid.UUID
	selectValues             sql.SelectValues
}

// LocationLayoutElementEdges holds the relations/edges for other nodes in the graph.
type LocationLayoutElementEdges struct {
	// Layout holds the value of the layout edge.
	Layout *LocationLayout `json:"layout,omitempty"`
	// Target holds the value of the target edge.
	Target *Entity `json:"target,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// LayoutOrErr returns the Layout value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LocationLayoutElementEdges) LayoutOrErr() (*LocationLayout, error) {
	if e.Layout != nil {
		return e.Layout, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: locationlayout.Label}
	}
	return nil, &NotLoadedError{edge: "layout"}
}

// TargetOrErr returns the Target value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LocationLayoutElementEdges) TargetOrErr() (*Entity, error) {
	if e.Target != nil {
		return e.Target, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: entity.Label}
	}
	return nil, &NotLoadedError{edge: "target"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LocationLayoutElement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case locationlayoutelement.FieldX, locationlayoutelement.FieldY, locationlayoutelement.FieldWidth, locationlayoutelement.FieldHeight, locationlayoutelement.FieldEndX, locationlayoutelement.FieldEndY, locationlayoutelement.FieldRotation:
			values[i] = new(sql.NullFloat64)
		case locationlayoutelement.FieldZOrder:
			values[i] = new(sql.NullInt64)
		case locationlayoutelement.FieldKind:
			values[i] = new(sql.NullString)
		case locationlayoutelement.FieldCreatedAt, locationlayoutelement.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case locationlayoutelement.FieldID:
			values[i] = new(uuid.UUID)
		case locationlayoutelement.ForeignKeys[0]: // entity_layout_placements
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case locationlayoutelement.ForeignKeys[1]: // location_layout_elements
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LocationLayoutElement fields.
func (_m *LocationLayoutElement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case locationlayoutelement.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case locationlayoutelement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case locationlayoutelement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case locationlayoutelement.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = locationlayoutelement.Kind(value.String)
			}
		case locationlayoutelement.FieldX:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field x", values[i])
			} else if value.Valid {
				_m.X = value.Float64
			}
		case locationlayoutelement.FieldY:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field y", values[i])
			} else if value.Valid {
				_m.Y = value.Float64
			}
		case locationlayoutelement.FieldWidth:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = value.Float64
			}
		case locationlayoutelement.FieldHeight:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = value.Float64
			}
		case locationlayoutelement.FieldEndX:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field end_x", values[i])
			} else if value.Valid {
				_m.EndX = value.Float64
			}
		case locationlayoutelement.FieldEndY:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field end_y", values[i])
			} else if value.Valid {
				_m.EndY = value.Float64
			}
		case locationlayoutelement.FieldRotation:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rotation", values[i])
			} else if value.Valid {
				_m.Rotation = value.Float64
			}
		case locationlayoutelement.FieldZOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field z_order", values[i])
			} else if value.Valid {
				_m.ZOrder = int(value.Int64)
			}
		case locationlayoutelement.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field entity_layout_placements", values[i])
			} else if value.Valid {
				_m.entity_layout_placements = new(uuid.UUID)
				*_m.entity_layout_placements = *value.S.(*uuid.UUID)
			}
		case locationlayoutelement.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field location_layout_elements", values[i])
			} else if value.Valid {
				_m.location_layout_elements = new(uuid.UUID)
				*_m.location_layout_elements = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LocationLayoutElement.
// This includes values selected through modifiers, order, etc.
func (_m *LocationLayoutElement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLayout queries the "layout" edge of the LocationLayoutElement entity.
func (_m *LocationLayoutElement) QueryLayout() *LocationLayoutQuery {
	return NewLocationLayoutElementClient(_m.config).QueryLayout(_m)
}

// QueryTarget queries the "target" edge of the LocationLayoutElement entity.
func (_m *LocationLayoutElement) QueryTarget() *EntityQuery {
	return NewLocationLayoutElementClient(_m.config).QueryTarget(_m)
}

// Update returns a builder for updating this LocationLayoutElement.
// Note that you need to call LocationLayoutElement.Unwrap() before calling this method if this LocationLayoutElement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LocationLayoutElement) Update() *LocationLayoutElementUpdateOne {
	return NewLocationLayoutElementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LocationLayoutElement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LocationLayoutElement) Unwrap() *LocationLayoutElement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LocationLayoutElement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LocationLayoutElement) String() string {
	var builder strings.Builder
	builder.WriteString("LocationLayoutElement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("x=")
	builder.WriteString(fmt.Sprintf("%v", _m.X))
	builder.WriteString(", ")
	builder.WriteString("y=")
	builder.WriteString(fmt.Sprintf("%v", _m.Y))
	builder.WriteString(", ")
	builder.WriteString("width=")
	builder.WriteString(fmt.Sprintf("%v", _m.Width))
	builder.WriteString(", ")
	builder.WriteString("height=")
	builder.WriteString(fmt.Sprintf("%v", _m.Height))
	builder.WriteString(", ")
	builder.WriteString("end_x=")
	builder.WriteString(fmt.Sprintf("%v", _m.EndX))
	builder.WriteString(", ")
	builder.WriteString("end_y=")
	builder.WriteString(fmt.Sprintf("%v", _m.EndY))
	builder.WriteString(", ")
	builder.WriteString("rotation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rotation))
	builder.WriteString(", ")
	builder.WriteString("z_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.ZOrder))
	builder.WriteByte(')')
	return builder.String()
}

// LocationLayoutElements is a parsable slice of LocationLayoutElement.
type LocationLayoutElements []*LocationLayoutElement
