// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayout"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayoutelement"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// LocationLayoutElementUpdate is the builder for updating LocationLayoutElement entities.
type LocationLayoutElementUpdate struct {
	config
	hooks    []Hook
	mutation *LocationLayoutElementMutation
}

// Where appends a list predicates to the LocationLayoutElementUpdate builder.
func (_u *LocationLayoutElementUpdate) Where(ps ...predicate.LocationLayoutElement) *LocationLayoutElementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LocationLayoutElementUpdate) SetUpdatedAt(v time.Time) *LocationLayoutElementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *LocationLayoutElementUpdate) SetKind(v locationlayoutelement.Kind) *LocationLayoutElementUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *LocationLayoutElementUpdate) SetNillableKind(v *locationlayoutelement.Kind) *LocationLayoutElementUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetX sets the "x" field.
func (_u *LocationLayoutElementUpdate) SetX(v float64) *LocationLayoutElementUpdate {
	_u.mutation.ResetX()
	_u.mutation.SetX(v)
	return _u
}

// SetNillableX sets the "x" field if the given value is not nil.
func (_u *LocationLayoutElementUpdate) SetNillableX(v *float64) *LocationLayoutElementUpdate {
	if v != nil {
		_u.SetX(*v)
	}
	return _u
}

// AddX adds value to the "x" field.
func (_u *LocationLayoutElementUpdate) AddX(v float64) *LocationLayoutElementUpdate {
	_u.mutation.AddX(v)
	return _u
}

// SetY sets the "y" field.
func (_u *LocationLayoutElementUpdate) SetY(v float64) *LocationLayoutElementUpdate {
	_u.mutation.ResetY()
	_u.mutation.SetY(v)
	return _u
}

// SetNillableY sets the "y" field if the given value is not nil.
func (_u *LocationLayoutElementUpdate) SetNillableY(v *float64) *LocationLayoutElementUpdate {
	if v != nil {
		_u.SetY(*v)
	}
	return _u
}

// AddY adds value to the "y" field.
func (_u *LocationLayoutElementUpdate) AddY(v float64) *LocationLayoutElementUpdate {
	_u.mutation.AddY(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *LocationLayoutElementUpdate) SetWidth(v float64) *LocationLayoutElementUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *LocationLayoutElementUpdate) SetNillableWidth(v *float64) *LocationLayoutElementUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *LocationLayoutElementUpdate) AddWidth(v float64) *LocationLayoutElementUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *LocationLayoutElementUpdate) SetHeight(v float64) *LocationLayoutElementUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *LocationLayoutElementUpdate) SetNillableHeight(v *float64) *LocationLayoutElementUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *LocationLayoutElementUpdate) AddHeight(v float64) *LocationLayoutElementUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// SetEndX sets the "end_x" field.
func (_u *LocationLayoutElementUpdate) SetEndX(v float64) *LocationLayoutElementUpdate {
	_u.mutation.ResetEndX()
	_u.mutation.SetEndX(v)
	return _u
}

// SetNillableEndX sets the "end_x" field if the given value is not nil.
func (_u *LocationLayoutElementUpdate) SetNillableEndX(v *float64) *LocationLayoutElementUpdate {
	if v != nil {
		_u.SetEndX(*v)
	}
	return _u
}

// AddEndX adds value to the "end_x" field.
func (_u *LocationLayoutElementUpdate) AddEndX(v float64) *LocationLayoutElementUpdate {
	_u.mutation.AddEndX(v)
	return _u
}

// SetEndY sets the "end_y" field.
func (_u *LocationLayoutElementUpdate) SetEndY(v float64) *LocationLayoutElementUpdate {
	_u.mutation.ResetEndY()
	_u.mutation.SetEndY(v)
	return _u
}

// SetNillableEndY sets the "end_y" field if the given value is not nil.
func (_u *LocationLayoutElementUpdate) SetNillableEndY(v *float64) *LocationLayoutElementUpdate {
	if v != nil {
		_u.SetEndY(*v)
	}
	return _u
}

// AddEndY adds value to the "end_y" field.
func (_u *LocationLayoutElementUpdate) AddEndY(v float64) *LocationLayoutElementUpdate {
	_u.mutation.AddEndY(v)
	return _u
}

// SetRotation sets the "rotation" field.
func (_u *LocationLayoutElementUpdate) SetRotation(v float64) *LocationLayoutElementUpdate {
	_u.mutation.ResetRotation()
	_u.mutation.SetRotation(v)
	return _u
}

// SetNillableRotation sets the "rotation" field if the given value is not nil.
func (_u *LocationLayoutElementUpdate) SetNillableRotation(v *float64) *LocationLayoutElementUpdate {
	if v != nil {
		_u.SetRotation(*v)
	}
	return _u
}

// AddRotation adds value to the "rotation" field.
func (_u *LocationLayoutElementUpdate) AddRotation(v float64) *LocationLayoutElementUpdate {
	_u.mutation.AddRotation(v)
	return _u
}

// SetZOrder sets the "z_order" field.
func (_u *LocationLayoutElementUpdate) SetZOrder(v int) *LocationLayoutElementUpdate {
	_u.mutation.ResetZOrder()
	_u.mutation.SetZOrder(v)
	return _u
}

// SetNillableZOrder sets the "z_order" field if the given value is not nil.
func (_u *LocationLayoutElementUpdate) SetNillableZOrder(v *int) *LocationLayoutElementUpdate {
	if v != nil {
		_u.SetZOrder(*v)
	}
	return _u
}

// AddZOrder adds value to the "z_order" field.
func (_u *LocationLayoutElementUpdate) AddZOrder(v int) *LocationLayoutElementUpdate {
	_u.mutation.AddZOrder(v)
	return _u
}

// SetLayoutID sets the "layout" edge to the LocationLayout entity by ID.
func (_u *LocationLayoutElementUpdate) SetLayoutID(id uuid.UUID) *LocationLayoutElementUpdate {
	_u.mutation.SetLayoutID(id)
	return _u
}

// SetLayout sets the "layout" edge to the LocationLayout entity.
func (_u *LocationLayoutElementUpdate) SetLayout(v *LocationLayout) *LocationLayoutElementUpdate {
	return _u.SetLayoutID(v.ID)
}

// SetTargetID sets the "target" edge to the Entity entity by ID.
func (_u *LocationLayoutElementUpdate) SetTargetID(id uuid.UUID) *LocationLayoutElementUpdate {
	_u.mutation.SetTargetID(id)
	return _u
}

// SetNillableTargetID sets the "target" edge to the Entity entity by ID if the given value is not nil.
func (_u *LocationLayoutElementUpdate) SetNillableTargetID(id *uuid.UUID) *LocationLayoutElementUpdate {
	if id != nil {
		_u = _u.SetTargetID(*id)
	}
	return _u
}

// SetTarget sets the "target" edge to the Entity entity.
func (_u *LocationLayoutElementUpdate) SetTarget(v *Entity) *LocationLayoutElementUpdate {
	return _u.SetTargetID(v.ID)
}

// Mutation returns the LocationLayoutElementMutation object of the builder.
func (_u *LocationLayoutElementUpdate) Mutation() *LocationLayoutElementMutation {
	return _u.mutation
}

// ClearLayout clears the "layout" edge to the LocationLayout entity.
func (_u *LocationLayoutElementUpdate) ClearLayout() *LocationLayoutElementUpdate {
	_u.mutation.ClearLayout()
	return _u
}

// ClearTarget clears the "target" edge to the Entity entity.
func (_u *LocationLayoutElementUpdate) ClearTarget() *LocationLayoutElementUpdate {
	_u.mutation.ClearTarget()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LocationLayoutElementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LocationLayoutElementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LocationLayoutElementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LocationLayoutElementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LocationLayoutElementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := locationlayoutelement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LocationLayoutElementUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := locationlayoutelement.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "LocationLayoutElement.kind": %w`, err)}
		}
	}
	if _u.mutation.LayoutCleared() && len(_u.mutation.LayoutIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LocationLayoutElement.layout"`)
	}
	return nil
}

func (_u *LocationLayoutElementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(locationlayoutelement.Table, locationlayoutelement.Columns, sqlgraph.NewFieldSpec(locationlayoutelement.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(locationlayoutelement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(locationlayoutelement.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.X(); ok {
		_spec.SetField(locationlayoutelement.FieldX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedX(); ok {
		_spec.AddField(locationlayoutelement.FieldX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Y(); ok {
		_spec.SetField(locationlayoutelement.FieldY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedY(); ok {
		_spec.AddField(locationlayoutelement.FieldY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(locationlayoutelement.FieldWidth, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(locationlayoutelement.FieldWidth, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(locationlayoutelement.FieldHeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(locationlayoutelement.FieldHeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EndX(); ok {
		_spec.SetField(locationlayoutelement.FieldEndX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEndX(); ok {
		_spec.AddField(locationlayoutelement.FieldEndX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EndY(); ok {
		_spec.SetField(locationlayoutelement.FieldEndY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEndY(); ok {
		_spec.AddField(locationlayoutelement.FieldEndY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Rotation(); ok {
		_spec.SetField(locationlayoutelement.FieldRotation, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRotation(); ok {
		_spec.AddField(locationlayoutelement.FieldRotation, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ZOrder(); ok {
		_spec.SetField(locationlayoutelement.FieldZOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedZOrder(); ok {
		_spec.AddField(locationlayoutelement.FieldZOrder, field.TypeInt, value)
	}
	if _u.mutation.LayoutCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationlayoutelement.LayoutTable,
			Columns: []string{locationlayoutelement.LayoutColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationlayout.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LayoutIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationlayoutelement.LayoutTable,
			Columns: []string{locationlayoutelement.LayoutColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationlayout.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationlayoutelement.TargetTable,
			Columns: []string{locationlayoutelement.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationlayoutelement.TargetTable,
			Columns: []string{locationlayoutelement.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{locationlayoutelement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LocationLayoutElementUpdateOne is the builder for updating a single LocationLayoutElement entity.
type LocationLayoutElementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LocationLayoutElementMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LocationLayoutElementUpdateOne) SetUpdatedAt(v time.Time) *LocationLayoutElementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *LocationLayoutElementUpdateOne) SetKind(v locationlayoutelement.Kind) *LocationLayoutElementUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *LocationLayoutElementUpdateOne) SetNillableKind(v *locationlayoutelement.Kind) *LocationLayoutElementUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetX sets the "x" field.
func (_u *LocationLayoutElementUpdateOne) SetX(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.ResetX()
	_u.mutation.SetX(v)
	return _u
}

// SetNillableX sets the "x" field if the given value is not nil.
func (_u *LocationLayoutElementUpdateOne) SetNillableX(v *float64) *LocationLayoutElementUpdateOne {
	if v != nil {
		_u.SetX(*v)
	}
	return _u
}

// AddX adds value to the "x" field.
func (_u *LocationLayoutElementUpdateOne) AddX(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.AddX(v)
	return _u
}

// SetY sets the "y" field.
func (_u *LocationLayoutElementUpdateOne) SetY(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.ResetY()
	_u.mutation.SetY(v)
	return _u
}

// SetNillableY sets the "y" field if the given value is not nil.
func (_u *LocationLayoutElementUpdateOne) SetNillableY(v *float64) *LocationLayoutElementUpdateOne {
	if v != nil {
		_u.SetY(*v)
	}
	return _u
}

// AddY adds value to the "y" field.
func (_u *LocationLayoutElementUpdateOne) AddY(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.AddY(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *LocationLayoutElementUpdateOne) SetWidth(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *LocationLayoutElementUpdateOne) SetNillableWidth(v *float64) *LocationLayoutElementUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *LocationLayoutElementUpdateOne) AddWidth(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *LocationLayoutElementUpdateOne) SetHeight(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *LocationLayoutElementUpdateOne) SetNillableHeight(v *float64) *LocationLayoutElementUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *LocationLayoutElementUpdateOne) AddHeight(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// SetEndX sets the "end_x" field.
func (_u *LocationLayoutElementUpdateOne) SetEndX(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.ResetEndX()
	_u.mutation.SetEndX(v)
	return _u
}

// SetNillableEndX sets the "end_x" field if the given value is not nil.
func (_u *LocationLayoutElementUpdateOne) SetNillableEndX(v *float64) *LocationLayoutElementUpdateOne {
	if v != nil {
		_u.SetEndX(*v)
	}
	return _u
}

// AddEndX adds value to the "end_x" field.
func (_u *LocationLayoutElementUpdateOne) AddEndX(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.AddEndX(v)
	return _u
}

// SetEndY sets the "end_y" field.
func (_u *LocationLayoutElementUpdateOne) SetEndY(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.ResetEndY()
	_u.mutation.SetEndY(v)
	return _u
}

// SetNillableEndY sets the "end_y" field if the given value is not nil.
func (_u *LocationLayoutElementUpdateOne) SetNillableEndY(v *float64) *LocationLayoutElementUpdateOne {
	if v != nil {
		_u.SetEndY(*v)
	}
	return _u
}

// AddEndY adds value to the "end_y" field.
func (_u *LocationLayoutElementUpdateOne) AddEndY(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.AddEndY(v)
	return _u
}

// SetRotation sets the "rotation" field.
func (_u *LocationLayoutElementUpdateOne) SetRotation(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.ResetRotation()
	_u.mutation.SetRotation(v)
	return _u
}

// SetNillableRotation sets the "rotation" field if the given value is not nil.
func (_u *LocationLayoutElementUpdateOne) SetNillableRotation(v *float64) *LocationLayoutElementUpdateOne {
	if v != nil {
		_u.SetRotation(*v)
	}
	return _u
}

// AddRotation adds value to the "rotation" field.
func (_u *LocationLayoutElementUpdateOne) AddRotation(v float64) *LocationLayoutElementUpdateOne {
	_u.mutation.AddRotation(v)
	return _u
}

// SetZOrder sets the "z_order" field.
func (_u *LocationLayoutElementUpdateOne) SetZOrder(v int) *LocationLayoutElementUpdateOne {
	_u.mutation.ResetZOrder()
	_u.mutation.SetZOrder(v)
	return _u
}

// SetNillableZOrder sets the "z_order" field if the given value is not nil.
func (_u *LocationLayoutElementUpdateOne) SetNillableZOrder(v *int) *LocationLayoutElementUpdateOne {
	if v != nil {
		_u.SetZOrder(*v)
	}
	return _u
}

// AddZOrder adds value to the "z_order" field.
func (_u *LocationLayoutElementUpdateOne) AddZOrder(v int) *LocationLayoutElementUpdateOne {
	_u.mutation.AddZOrder(v)
	return _u
}

// SetLayoutID sets the "layout" edge to the LocationLayout entity by ID.
func (_u *LocationLayoutElementUpdateOne) SetLayoutID(id uuid.UUID) *LocationLayoutElementUpdateOne {
	_u.mutation.SetLayoutID(id)
	return _u
}

// SetLayout sets the "layout" edge to the LocationLayout entity.
func (_u *LocationLayoutElementUpdateOne) SetLayout(v *LocationLayout) *LocationLayoutElementUpdateOne {
	return _u.SetLayoutID(v.ID)
}

// SetTargetID sets the "target" edge to the Entity entity by ID.
func (_u *LocationLayoutElementUpdateOne) SetTargetID(id uuid.UUID) *LocationLayoutElementUpdateOne {
	_u.mutation.SetTargetID(id)
	return _u
}

// SetNillableTargetID sets the "target" edge to the Entity entity by ID if the given value is not nil.
func (_u *LocationLayoutElementUpdateOne) SetNillableTargetID(id *uuid.UUID) *LocationLayoutElementUpdateOne {
	if id != nil {
		_u = _u.SetTargetID(*id)
	}
	return _u
}

// SetTarget sets the "target" edge to the Entity entity.
func (_u *LocationLayoutElementUpdateOne) SetTarget(v *Entity) *LocationLayoutElementUpdateOne {
	return _u.SetTargetID(v.ID)
}

// Mutation returns the LocationLayoutElementMutation object of the builder.
func (_u *LocationLayoutElementUpdateOne) Mutation() *LocationLayoutElementMutation {
	return _u.mutation
}

// ClearLayout clears the "layout" edge to the LocationLayout entity.
func (_u *LocationLayoutElementUpdateOne) ClearLayout() *LocationLayoutElementUpdateOne {
	_u.mutation.ClearLayout()
	return _u
}

// ClearTarget clears the "target" edge to the Entity entity.
func (_u *LocationLayoutElementUpdateOne) ClearTarget() *LocationLayoutElementUpdateOne {
	_u.mutation.ClearTarget()
	return _u
}

// Where appends a list predicates to the LocationLayoutElementUpdate builder.
func (_u *LocationLayoutElementUpdateOne) Where(ps ...predicate.LocationLayoutElement) *LocationLayoutElementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LocationLayoutElementUpdateOne) Select(field string, fields ...string) *LocationLayoutElementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LocationLayoutElement entity.
func (_u *LocationLayoutElementUpdateOne) Save(ctx context.Context) (*LocationLayoutElement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LocationLayoutElementUpdateOne) SaveX(ctx context.Context) *LocationLayoutElement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LocationLayoutElementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LocationLayoutElementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LocationLayoutElementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := locationlayoutelement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LocationLayoutElementUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := locationlayoutelement.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "LocationLayoutElement.kind": %w`, err)}
		}
	}
	if _u.mutation.LayoutCleared() && len(_u.mutation.LayoutIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LocationLayoutElement.layout"`)
	}
	return nil
}

func (_u *LocationLayoutElementUpdateOne) sqlSave(ctx context.Context) (_node *LocationLayoutElement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(locationlayoutelement.Table, locationlayoutelement.Columns, sqlgraph.NewFieldSpec(locationlayoutelement.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LocationLayoutElement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, locationlayoutelement.FieldID)
		for _, f := range fields {
			if !locationlayoutelement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != locationlayoutelement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(locationlayoutelement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(locationlayoutelement.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.X(); ok {
		_spec.SetField(locationlayoutelement.FieldX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedX(); ok {
		_spec.AddField(locationlayoutelement.FieldX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Y(); ok {
		_spec.SetField(locationlayoutelement.FieldY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedY(); ok {
		_spec.AddField(locationlayoutelement.FieldY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(locationlayoutelement.FieldWidth, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(locationlayoutelement.FieldWidth, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(locationlayoutelement.FieldHeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(locationlayoutelement.FieldHeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EndX(); ok {
		_spec.SetField(locationlayoutelement.FieldEndX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEndX(); ok {
		_spec.AddField(locationlayoutelement.FieldEndX, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EndY(); ok {
		_spec.SetField(locationlayoutelement.FieldEndY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEndY(); ok {
		_spec.AddField(locationlayoutelement.FieldEndY, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Rotation(); ok {
		_spec.SetField(locationlayoutelement.FieldRotation, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRotation(); ok {
		_spec.AddField(locationlayoutelement.FieldRotation, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ZOrder(); ok {
		_spec.SetField(locationlayoutelement.FieldZOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedZOrder(); ok {
		_spec.AddField(locationlayoutelement.FieldZOrder, field.TypeInt, value)
	}
	if _u.mutation.LayoutCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationlayoutelement.LayoutTable,
			Columns: []string{locationlayoutelement.LayoutColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationlayout.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LayoutIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationlayoutelement.LayoutTable,
			Columns: []string{locationlayoutelement.LayoutColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationlayout.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationlayoutelement.TargetTable,
			Columns: []string{locationlayoutelement.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   locationlayoutelement.TargetTable,
			Columns: []string{locationlayoutelement.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LocationLayoutElement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{locationlayoutelement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
