// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayoutelement"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// LocationLayoutElementDelete is the builder for deleting a LocationLayoutElement entity.
type LocationLayoutElementDelete struct {
	config
	hooks    []Hook
	mutation *LocationLayoutElementMutation
}

// Where appends a list predicates to the LocationLayoutElementDelete builder.
func (_d *LocationLayoutElementDelete) Where(ps ...predicate.LocationLayoutElement) *LocationLayoutElementDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LocationLayoutElementDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LocationLayoutElementDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LocationLayoutElementDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(locationlayoutelement.Table, sqlgraph.NewFieldSpec(locationlayoutelement.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LocationLayoutElementDeleteOne is the builder for deleting a single LocationLayoutElement entity.
type LocationLayoutElementDeleteOne struct {
	_d *LocationLayoutElementDelete
}

// Where appends a list predicates to the LocationLayoutElementDelete builder.
func (_d *LocationLayoutElementDeleteOne) Where(ps ...predicate.LocationLayoutElement) *LocationLayoutElementDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LocationLayoutElementDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{locationlayoutelement.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LocationLayoutElementDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
