// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayout"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/locationlayoutelement"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// LocationLayoutElementQuery is the builder for querying LocationLayoutElement entities.
type LocationLayoutElementQuery struct {
	config
	ctx        *QueryContext
	order      []locationlayoutelement.OrderOption
	inters     []Interceptor
	predicates []predicate.LocationLayoutElement
	withLayout *LocationLayoutQuery
	withTarget *EntityQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LocationLayoutElementQuery builder.
func (_q *LocationLayoutElementQuery) Where(ps ...predicate.LocationLayoutElement) *LocationLayoutElementQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *LocationLayoutElementQuery) Limit(limit int) *LocationLayoutElementQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *LocationLayoutElementQuery) Offset(offset int) *LocationLayoutElementQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *LocationLayoutElementQuery) Unique(unique bool) *LocationLayoutElementQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *LocationLayoutElementQuery) Order(o ...locationlayoutelement.OrderOption) *LocationLayoutElementQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryLayout chains the current query on the "layout" edge.
func (_q *LocationLayoutElementQuery) QueryLayout() *LocationLayoutQuery {
	query := (&LocationLayoutClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(locationlayoutelement.Table, locationlayoutelement.FieldID, selector),
			sqlgraph.To(locationlayout.Table, locationlayout.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, locationlayoutelement.LayoutTable, locationlayoutelement.LayoutColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTarget chains the current query on the "target" edge.
func (_q *LocationLayoutElementQuery) QueryTarget() *EntityQuery {
	query := (&EntityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(locationlayoutelement.Table, locationlayoutelement.FieldID, selector),
			sqlgraph.To(entity.Table, entity.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, locationlayoutelement.TargetTable, locationlayoutelement.TargetColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LocationLayoutElement entity from the query.
// Returns a *NotFoundError when no LocationLayoutElement was found.
func (_q *LocationLayoutElementQuery) First(ctx context.Context) (*LocationLayoutElement, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{locationlayoutelement.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *LocationLayoutElementQuery) FirstX(ctx context.Context) *LocationLayoutElement {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LocationLayoutElement ID from the query.
// Returns a *NotFoundError when no LocationLayoutElement ID was found.
func (_q *LocationLayoutElementQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{locationlayoutelement.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *LocationLayoutElementQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LocationLayoutElement entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LocationLayoutElement entity is found.
// Returns a *NotFoundError when no LocationLayoutElement entities are found.
func (_q *LocationLayoutElementQuery) Only(ctx context.Context) (*LocationLayoutElement, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{locationlayoutelement.Label}
	default:
		return nil, &NotSingularError{locationlayoutelement.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *LocationLayoutElementQuery) OnlyX(ctx context.Context) *LocationLayoutElement {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LocationLayoutElement ID in the query.
// Returns a *NotSingularError when more than one LocationLayoutElement ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *LocationLayoutElementQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{locationlayoutelement.Label}
	default:
		err = &NotSingularError{locationlayoutelement.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *LocationLayoutElementQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LocationLayoutElements.
func (_q *LocationLayoutElementQuery) All(ctx context.Context) ([]*LocationLayoutElement, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LocationLayoutElement, *LocationLayoutElementQuery]()
	return withInterceptors[[]*LocationLayoutElement](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *LocationLayoutElementQuery) AllX(ctx context.Context) []*LocationLayoutElement {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LocationLayoutElement IDs.
func (_q *LocationLayoutElementQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(locationlayoutelement.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *LocationLayoutElementQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *LocationLayoutElementQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*LocationLayoutElementQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *LocationLayoutElementQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *LocationLayoutElementQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *LocationLayoutElementQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LocationLayoutElementQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *LocationLayoutElementQuery) Clone() *LocationLayoutElementQuery {
	if _q == nil {
		return nil
	}
	return &LocationLayoutElementQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]locationlayoutelement.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.LocationLayoutElement{}, _q.predicates...),
		withLayout: _q.withLayout.Clone(),
		withTarget: _q.withTarget.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithLayout tells the query-builder to eager-load the nodes that are connected to
// the "layout" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LocationLayoutElementQuery) WithLayout(opts ...func(*LocationLayoutQuery)) *LocationLayoutElementQuery {
	query := (&LocationLayoutClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLayout = query
	return _q
}

// WithTarget tells the query-builder to eager-load the nodes that are connected to
// the "target" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LocationLayoutElementQuery) WithTarget(opts ...func(*EntityQuery)) *LocationLayoutElementQuery {
	query := (&EntityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTarget = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LocationLayoutElement.Query().
//		GroupBy(locationlayoutelement.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *LocationLayoutElementQuery) GroupBy(field string, fields ...string) *LocationLayoutElementGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LocationLayoutElementGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = locationlayoutelement.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.LocationLayoutElement.Query().
//		Select(locationlayoutelement.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *LocationLayoutElementQuery) Select(fields ...string) *LocationLayoutElementSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &LocationLayoutElementSelect{LocationLayoutElementQuery: _q}
	sbuild.label = locationlayoutelement.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LocationLayoutElementSelect configured with the given aggregations.
func (_q *LocationLayoutElementQuery) Aggregate(fns ...AggregateFunc) *LocationLayoutElementSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *LocationLayoutElementQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !locationlayoutelement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *LocationLayoutElementQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LocationLayoutElement, error) {
	var (
		nodes       = []*LocationLayoutElement{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withLayout != nil,
			_q.withTarget != nil,
		}
	)
	if _q.withLayout != nil || _q.withTarget != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, locationlayoutelement.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LocationLayoutElement).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LocationLayoutElement{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withLayout; query != nil {
		if err := _q.loadLayout(ctx, query, nodes, nil,
			func(n *LocationLayoutElement, e *LocationLayout) { n.Edges.Layout = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTarget; query != nil {
		if err := _q.loadTarget(ctx, query, nodes, nil,
			func(n *LocationLayoutElement, e *Entity) { n.Edges.Target = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *LocationLayoutElementQuery) loadLayout(ctx context.Context, query *LocationLayoutQuery, nodes []*LocationLayoutElement, init func(*LocationLayoutElement), assign func(*LocationLayoutElement, *LocationLayout)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*LocationLayoutElement)
	for i := range nodes {
		if nodes[i].location_layout_elements == nil {
			continue
		}
		fk := *nodes[i].location_layout_elements
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(locationlayout.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "location_layout_elements" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *LocationLayoutElementQuery) loadTarget(ctx context.Context, query *EntityQuery, nodes []*LocationLayoutElement, init func(*LocationLayoutElement), assign func(*LocationLayoutElement, *Entity)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*LocationLayoutElement)
	for i := range nodes {
		if nodes[i].entity_layout_placements == nil {
			continue
		}
		fk := *nodes[i].entity_layout_placements
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(entity.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "entity_layout_placements" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *LocationLayoutElementQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *LocationLayoutElementQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(locationlayoutelement.Table, locationlayoutelement.Columns, sqlgraph.NewFieldSpec(locationlayoutelement.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, locationlayoutelement.FieldID)
		for i := range fields {
			if fields[i] != locationlayoutelement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *LocationLayoutElementQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(locationlayoutelement.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = locationlayoutelement.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LocationLayoutElementGroupBy is the group-by builder for LocationLayoutElement entities.
type LocationLayoutElementGroupBy struct {
	selector
	build *LocationLayoutElementQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *LocationLayoutElementGroupBy) Aggregate(fns ...AggregateFunc) *LocationLayoutElementGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *LocationLayoutElementGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LocationLayoutElementQuery, *LocationLayoutElementGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *LocationLayoutElementGroupBy) sqlScan(ctx context.Context, root *LocationLayoutElementQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LocationLayoutElementSelect is the builder for selecting fields of LocationLayoutElement entities.
type LocationLayoutElementSelect struct {
	*LocationLayoutElementQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *LocationLayoutElementSelect) Aggregate(fns ...AggregateFunc) *LocationLayoutElementSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *LocationLayoutElementSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LocationLayoutElementQuery, *LocationLayoutElementSelect](ctx, _s.LocationLayoutElementQuery, _s, _s.inters, v)
}

func (_s *LocationLayoutElementSelect) sqlScan(ctx context.Context, root *LocationLayoutElementQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
