// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/qrlogintokens"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// QRLoginTokensCreate is the builder for creating a QRLoginTokens entity.
type QRLoginTokensCreate struct {
	config
	mutation *QRLoginTokensMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *QRLoginTokensCreate) SetCreatedAt(v time.Time) *QRLoginTokensCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QRLoginTokensCreate) SetNillableCreatedAt(v *time.Time) *QRLoginTokensCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QRLoginTokensCreate) SetUpdatedAt(v time.Time) *QRLoginTokensCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QRLoginTokensCreate) SetNillableUpdatedAt(v *time.Time) *QRLoginTokensCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *QRLoginTokensCreate) SetUserID(v uuid.UUID) *QRLoginTokensCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetToken sets the "token" field.
func (_c *QRLoginTokensCreate) SetToken(v []byte) *QRLoginTokensCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *QRLoginTokensCreate) SetExpiresAt(v time.Time) *QRLoginTokensCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *QRLoginTokensCreate) SetNillableExpiresAt(v *time.Time) *QRLoginTokensCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *QRLoginTokensCreate) SetUsedAt(v time.Time) *QRLoginTokensCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *QRLoginTokensCreate) SetNillableUsedAt(v *time.Time) *QRLoginTokensCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QRLoginTokensCreate) SetID(v uuid.UUID) *QRLoginTokensCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *QRLoginTokensCreate) SetNillableID(v *uuid.UUID) *QRLoginTokensCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *QRLoginTokensCreate) SetUser(v *User) *QRLoginTokensCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the QRLoginTokensMutation object of the builder.
func (_c *QRLoginTokensCreate) Mutation() *QRLoginTokensMutation {
	return _c.mutation
}

// Save creates the QRLoginTokens in the database.
func (_c *QRLoginTokensCreate) Save(ctx context.Context) (*QRLoginTokens, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QRLoginTokensCreate) SaveX(ctx context.Context) *QRLoginTokens {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QRLoginTokensCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QRLoginTokensCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QRLoginTokensCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := qrlogintokens.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := qrlogintokens.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		v := qrlogintokens.DefaultExpiresAt()
		_c.mutation.SetExpiresAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := qrlogintokens.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QRLoginTokensCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QRLoginTokens.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "QRLoginTokens.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "QRLoginTokens.user_id"`)}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "QRLoginTokens.token"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "QRLoginTokens.expires_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "QRLoginTokens.user"`)}
	}
	return nil
}

func (_c *QRLoginTokensCreate) sqlSave(ctx context.Context) (*QRLoginTokens, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QRLoginTokensCreate) createSpec() (*QRLoginTokens, *sqlgraph.CreateSpec) {
	var (
		_node = &QRLoginTokens{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(qrlogintokens.Table, sqlgraph.NewFieldSpec(qrlogintokens.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(qrlogintokens.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(qrlogintokens.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(qrlogintokens.FieldToken, field.TypeBytes, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(qrlogintokens.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(qrlogintokens.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   qrlogintokens.UserTable,
			Columns: []string{qrlogintokens.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QRLoginTokensCreateBulk is the builder for creating many QRLoginTokens entities in bulk.
type QRLoginTokensCreateBulk struct {
	config
	err      error
	builders []*QRLoginTokensCreate
}

// Save creates the QRLoginTokens entities in the database.
func (_c *QRLoginTokensCreateBulk) Save(ctx context.Context) ([]*QRLoginTokens, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*QRLoginTokens, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QRLoginTokensMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QRLoginTokensCreateBulk) SaveX(ctx context.Context) []*QRLoginTokens {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QRLoginTokensCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QRLoginTokensCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
