// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/qrlogintokens"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// QRLoginTokensUpdate is the builder for updating QRLoginTokens entities.
type QRLoginTokensUpdate struct {
	config
	hooks    []Hook
	mutation *QRLoginTokensMutation
}

// Where appends a list predicates to the QRLoginTokensUpdate builder.
func (_u *QRLoginTokensUpdate) Where(ps ...predicate.QRLoginTokens) *QRLoginTokensUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QRLoginTokensUpdate) SetUpdatedAt(v time.Time) *QRLoginTokensUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *QRLoginTokensUpdate) SetUserID(v uuid.UUID) *QRLoginTokensUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *QRLoginTokensUpdate) SetNillableUserID(v *uuid.UUID) *QRLoginTokensUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *QRLoginTokensUpdate) SetToken(v []byte) *QRLoginTokensUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *QRLoginTokensUpdate) SetExpiresAt(v time.Time) *QRLoginTokensUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *QRLoginTokensUpdate) SetNillableExpiresAt(v *time.Time) *QRLoginTokensUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *QRLoginTokensUpdate) SetUsedAt(v time.Time) *QRLoginTokensUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *QRLoginTokensUpdate) SetNillableUsedAt(v *time.Time) *QRLoginTokensUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *QRLoginTokensUpdate) ClearUsedAt() *QRLoginTokensUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *QRLoginTokensUpdate) SetUser(v *User) *QRLoginTokensUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the QRLoginTokensMutation object of the builder.
func (_u *QRLoginTokensUpdate) Mutation() *QRLoginTokensMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *QRLoginTokensUpdate) ClearUser() *QRLoginTokensUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QRLoginTokensUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QRLoginTokensUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QRLoginTokensUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QRLoginTokensUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QRLoginTokensUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := qrlogintokens.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QRLoginTokensUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QRLoginTokens.user"`)
	}
	return nil
}

func (_u *QRLoginTokensUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(qrlogintokens.Table, qrlogintokens.Columns, sqlgraph.NewFieldSpec(qrlogintokens.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(qrlogintokens.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(qrlogintokens.FieldToken, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(qrlogintokens.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(qrlogintokens.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(qrlogintokens.FieldUsedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   qrlogintokens.UserTable,
			Columns: []string{qrlogintokens.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   qrlogintokens.UserTable,
			Columns: []string{qrlogintokens.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{qrlogintokens.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QRLoginTokensUpdateOne is the builder for updating a single QRLoginTokens entity.
type QRLoginTokensUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QRLoginTokensMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QRLoginTokensUpdateOne) SetUpdatedAt(v time.Time) *QRLoginTokensUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *QRLoginTokensUpdateOne) SetUserID(v uuid.UUID) *QRLoginTokensUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *QRLoginTokensUpdateOne) SetNillableUserID(v *uuid.UUID) *QRLoginTokensUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *QRLoginTokensUpdateOne) SetToken(v []byte) *QRLoginTokensUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *QRLoginTokensUpdateOne) SetExpiresAt(v time.Time) *QRLoginTokensUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *QRLoginTokensUpdateOne) SetNillableExpiresAt(v *time.Time) *QRLoginTokensUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *QRLoginTokensUpdateOne) SetUsedAt(v time.Time) *QRLoginTokensUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *QRLoginTokensUpdateOne) SetNillableUsedAt(v *time.Time) *QRLoginTokensUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *QRLoginTokensUpdateOne) ClearUsedAt() *QRLoginTokensUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *QRLoginTokensUpdateOne) SetUser(v *User) *QRLoginTokensUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the QRLoginTokensMutation object of the builder.
func (_u *QRLoginTokensUpdateOne) Mutation() *QRLoginTokensMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *QRLoginTokensUpdateOne) ClearUser() *QRLoginTokensUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the QRLoginTokensUpdate builder.
func (_u *QRLoginTokensUpdateOne) Where(ps ...predicate.QRLoginTokens) *QRLoginTokensUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QRLoginTokensUpdateOne) Select(field string, fields ...string) *QRLoginTokensUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QRLoginTokens entity.
func (_u *QRLoginTokensUpdateOne) Save(ctx context.Context) (*QRLoginTokens, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QRLoginTokensUpdateOne) SaveX(ctx context.Context) *QRLoginTokens {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QRLoginTokensUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QRLoginTokensUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QRLoginTokensUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := qrlogintokens.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QRLoginTokensUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QRLoginTokens.user"`)
	}
	return nil
}

func (_u *QRLoginTokensUpdateOne) sqlSave(ctx context.Context) (_node *QRLoginTokens, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(qrlogintokens.Table, qrlogintokens.Columns, sqlgraph.NewFieldSpec(qrlogintokens.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QRLoginTokens.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, qrlogintokens.FieldID)
		for _, f := range fields {
			if !qrlogintokens.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != qrlogintokens.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(qrlogintokens.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(qrlogintokens.FieldToken, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(qrlogintokens.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(qrlogintokens.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(qrlogintokens.FieldUsedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   qrlogintokens.UserTable,
			Columns: []string{qrlogintokens.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   qrlogintokens.UserTable,
			Columns: []string{qrlogintokens.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &QRLoginTokens{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{qrlogintokens.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
