// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/qrlogintokens"
)

// QRLoginTokensDelete is the builder for deleting a QRLoginTokens entity.
type QRLoginTokensDelete struct {
	config
	hooks    []Hook
	mutation *QRLoginTokensMutation
}

// Where appends a list predicates to the QRLoginTokensDelete builder.
func (_d *QRLoginTokensDelete) Where(ps ...predicate.QRLoginTokens) *QRLoginTokensDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *QRLoginTokensDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QRLoginTokensDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *QRLoginTokensDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(qrlogintokens.Table, sqlgraph.NewFieldSpec(qrlogintokens.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// QRLoginTokensDeleteOne is the builder for deleting a single QRLoginTokens entity.
type QRLoginTokensDeleteOne struct {
	_d *QRLoginTokensDelete
}

// Where appends a list predicates to the QRLoginTokensDelete builder.
func (_d *QRLoginTokensDeleteOne) Where(ps ...predicate.QRLoginTokens) *QRLoginTokensDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *QRLoginTokensDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{qrlogintokens.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QRLoginTokensDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
