// Code generated by ent, DO NOT EDIT.

package entitystocktransaction

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the entitystocktransaction type in the database.
	Label = "entity_stock_transaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldActorID holds the string denoting the actor_id field in the database.
	FieldActorID = "actor_id"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldWorkflow holds the string denoting the workflow field in the database.
	FieldWorkflow = "workflow"
	// FieldSourceLocationID holds the string denoting the source_location_id field in the database.
	FieldSourceLocationID = "source_location_id"
	// FieldDestinationLocationID holds the string denoting the destination_location_id field in the database.
	FieldDestinationLocationID = "destination_location_id"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldBeforeTotal holds the string denoting the before_total field in the database.
	FieldBeforeTotal = "before_total"
	// FieldAfterTotal holds the string denoting the after_total field in the database.
	FieldAfterTotal = "after_total"
	// FieldSourceBefore holds the string denoting the source_before field in the database.
	FieldSourceBefore = "source_before"
	// FieldSourceAfter holds the string denoting the source_after field in the database.
	FieldSourceAfter = "source_after"
	// FieldDestinationBefore holds the string denoting the destination_before field in the database.
	FieldDestinationBefore = "destination_before"
	// FieldDestinationAfter holds the string denoting the destination_after field in the database.
	FieldDestinationAfter = "destination_after"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldRequestHash holds the string denoting the request_hash field in the database.
	FieldRequestHash = "request_hash"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeEntity holds the string denoting the entity edge name in mutations.
	EdgeEntity = "entity"
	// Table holds the table name of the entitystocktransaction in the database.
	Table = "entity_stock_transactions"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "entity_stock_transactions"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// EntityTable is the table that holds the entity relation/edge.
	EntityTable = "entity_stock_transactions"
	// EntityInverseTable is the table name for the Entity entity.
	// It exists in this package in order to avoid circular dependency with the "entity" package.
	EntityInverseTable = "entities"
	// EntityColumn is the table column denoting the entity relation/edge.
	EntityColumn = "entity_id"
)

// Columns holds all SQL columns for entitystocktransaction fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldGroupID,
	FieldEntityID,
	FieldActorID,
	FieldOperation,
	FieldWorkflow,
	FieldSourceLocationID,
	FieldDestinationLocationID,
	FieldQuantity,
	FieldBeforeTotal,
	FieldAfterTotal,
	FieldSourceBefore,
	FieldSourceAfter,
	FieldDestinationBefore,
	FieldDestinationAfter,
	FieldReason,
	FieldIdempotencyKey,
	FieldRequestHash,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// WorkflowValidator is a validator for the "workflow" field. It is called by the builders before save.
	WorkflowValidator func(string) error
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// RequestHashValidator is a validator for the "request_hash" field. It is called by the builders before save.
	RequestHashValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Operation defines the type for the "operation" enum field.
type Operation string

// Operation values.
const (
	OperationAdjust          Operation = "adjust"
	OperationSet             Operation = "set"
	OperationTransfer        Operation = "transfer"
	OperationResolveTransfer Operation = "resolve_transfer"
	OperationResolveRemove   Operation = "resolve_remove"
	OperationLegacy          Operation = "legacy"
)

func (o Operation) String() string {
	return string(o)
}

// OperationValidator is a validator for the "operation" field enum values. It is called by the builders before save.
func OperationValidator(o Operation) error {
	switch o {
	case OperationAdjust, OperationSet, OperationTransfer, OperationResolveTransfer, OperationResolveRemove, OperationLegacy:
		return nil
	default:
		return fmt.Errorf("entitystocktransaction: invalid enum value for operation field: %q", o)
	}
}

// OrderOption defines the ordering options for the EntityStockTransaction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByActorID orders the results by the actor_id field.
func ByActorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorID, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByWorkflow orders the results by the workflow field.
func ByWorkflow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflow, opts...).ToFunc()
}

// BySourceLocationID orders the results by the source_location_id field.
func BySourceLocationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceLocationID, opts...).ToFunc()
}

// ByDestinationLocationID orders the results by the destination_location_id field.
func ByDestinationLocationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestinationLocationID, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByBeforeTotal orders the results by the before_total field.
func ByBeforeTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBeforeTotal, opts...).ToFunc()
}

// ByAfterTotal orders the results by the after_total field.
func ByAfterTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAfterTotal, opts...).ToFunc()
}

// BySourceBefore orders the results by the source_before field.
func BySourceBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceBefore, opts...).ToFunc()
}

// BySourceAfter orders the results by the source_after field.
func BySourceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceAfter, opts...).ToFunc()
}

// ByDestinationBefore orders the results by the destination_before field.
func ByDestinationBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestinationBefore, opts...).ToFunc()
}

// ByDestinationAfter orders the results by the destination_after field.
func ByDestinationAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestinationAfter, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByRequestHash orders the results by the request_hash field.
func ByRequestHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestHash, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByEntityField orders the results by entity field.
func ByEntityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntityStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newEntityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EntityTable, EntityColumn),
	)
}
