// Code generated by ent, DO NOT EDIT.

package entitystocktransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldGroupID, v))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldEntityID, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldActorID, v))
}

// Workflow applies equality check predicate on the "workflow" field. It's identical to WorkflowEQ.
func Workflow(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldWorkflow, v))
}

// SourceLocationID applies equality check predicate on the "source_location_id" field. It's identical to SourceLocationIDEQ.
func SourceLocationID(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldSourceLocationID, v))
}

// DestinationLocationID applies equality check predicate on the "destination_location_id" field. It's identical to DestinationLocationIDEQ.
func DestinationLocationID(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldDestinationLocationID, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldQuantity, v))
}

// BeforeTotal applies equality check predicate on the "before_total" field. It's identical to BeforeTotalEQ.
func BeforeTotal(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldBeforeTotal, v))
}

// AfterTotal applies equality check predicate on the "after_total" field. It's identical to AfterTotalEQ.
func AfterTotal(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldAfterTotal, v))
}

// SourceBefore applies equality check predicate on the "source_before" field. It's identical to SourceBeforeEQ.
func SourceBefore(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldSourceBefore, v))
}

// SourceAfter applies equality check predicate on the "source_after" field. It's identical to SourceAfterEQ.
func SourceAfter(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldSourceAfter, v))
}

// DestinationBefore applies equality check predicate on the "destination_before" field. It's identical to DestinationBeforeEQ.
func DestinationBefore(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldDestinationBefore, v))
}

// DestinationAfter applies equality check predicate on the "destination_after" field. It's identical to DestinationAfterEQ.
func DestinationAfter(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldDestinationAfter, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldReason, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldIdempotencyKey, v))
}

// RequestHash applies equality check predicate on the "request_hash" field. It's identical to RequestHashEQ.
func RequestHash(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldRequestHash, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldGroupID, vs...))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldEntityID, vs...))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldActorID, v))
}

// ActorIDIsNil applies the IsNil predicate on the "actor_id" field.
func ActorIDIsNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIsNull(FieldActorID))
}

// ActorIDNotNil applies the NotNil predicate on the "actor_id" field.
func ActorIDNotNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotNull(FieldActorID))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v Operation) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v Operation) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...Operation) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...Operation) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldOperation, vs...))
}

// WorkflowEQ applies the EQ predicate on the "workflow" field.
func WorkflowEQ(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldWorkflow, v))
}

// WorkflowNEQ applies the NEQ predicate on the "workflow" field.
func WorkflowNEQ(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldWorkflow, v))
}

// WorkflowIn applies the In predicate on the "workflow" field.
func WorkflowIn(vs ...string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldWorkflow, vs...))
}

// WorkflowNotIn applies the NotIn predicate on the "workflow" field.
func WorkflowNotIn(vs ...string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldWorkflow, vs...))
}

// WorkflowGT applies the GT predicate on the "workflow" field.
func WorkflowGT(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldWorkflow, v))
}

// WorkflowGTE applies the GTE predicate on the "workflow" field.
func WorkflowGTE(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldWorkflow, v))
}

// WorkflowLT applies the LT predicate on the "workflow" field.
func WorkflowLT(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldWorkflow, v))
}

// WorkflowLTE applies the LTE predicate on the "workflow" field.
func WorkflowLTE(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldWorkflow, v))
}

// WorkflowContains applies the Contains predicate on the "workflow" field.
func WorkflowContains(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldContains(FieldWorkflow, v))
}

// WorkflowHasPrefix applies the HasPrefix predicate on the "workflow" field.
func WorkflowHasPrefix(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldHasPrefix(FieldWorkflow, v))
}

// WorkflowHasSuffix applies the HasSuffix predicate on the "workflow" field.
func WorkflowHasSuffix(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldHasSuffix(FieldWorkflow, v))
}

// WorkflowIsNil applies the IsNil predicate on the "workflow" field.
func WorkflowIsNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIsNull(FieldWorkflow))
}

// WorkflowNotNil applies the NotNil predicate on the "workflow" field.
func WorkflowNotNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotNull(FieldWorkflow))
}

// WorkflowEqualFold applies the EqualFold predicate on the "workflow" field.
func WorkflowEqualFold(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEqualFold(FieldWorkflow, v))
}

// WorkflowContainsFold applies the ContainsFold predicate on the "workflow" field.
func WorkflowContainsFold(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldContainsFold(FieldWorkflow, v))
}

// SourceLocationIDEQ applies the EQ predicate on the "source_location_id" field.
func SourceLocationIDEQ(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldSourceLocationID, v))
}

// SourceLocationIDNEQ applies the NEQ predicate on the "source_location_id" field.
func SourceLocationIDNEQ(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldSourceLocationID, v))
}

// SourceLocationIDIn applies the In predicate on the "source_location_id" field.
func SourceLocationIDIn(vs ...uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldSourceLocationID, vs...))
}

// SourceLocationIDNotIn applies the NotIn predicate on the "source_location_id" field.
func SourceLocationIDNotIn(vs ...uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldSourceLocationID, vs...))
}

// SourceLocationIDGT applies the GT predicate on the "source_location_id" field.
func SourceLocationIDGT(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldSourceLocationID, v))
}

// SourceLocationIDGTE applies the GTE predicate on the "source_location_id" field.
func SourceLocationIDGTE(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldSourceLocationID, v))
}

// SourceLocationIDLT applies the LT predicate on the "source_location_id" field.
func SourceLocationIDLT(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldSourceLocationID, v))
}

// SourceLocationIDLTE applies the LTE predicate on the "source_location_id" field.
func SourceLocationIDLTE(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldSourceLocationID, v))
}

// SourceLocationIDIsNil applies the IsNil predicate on the "source_location_id" field.
func SourceLocationIDIsNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIsNull(FieldSourceLocationID))
}

// SourceLocationIDNotNil applies the NotNil predicate on the "source_location_id" field.
func SourceLocationIDNotNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotNull(FieldSourceLocationID))
}

// DestinationLocationIDEQ applies the EQ predicate on the "destination_location_id" field.
func DestinationLocationIDEQ(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldDestinationLocationID, v))
}

// DestinationLocationIDNEQ applies the NEQ predicate on the "destination_location_id" field.
func DestinationLocationIDNEQ(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldDestinationLocationID, v))
}

// DestinationLocationIDIn applies the In predicate on the "destination_location_id" field.
func DestinationLocationIDIn(vs ...uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldDestinationLocationID, vs...))
}

// DestinationLocationIDNotIn applies the NotIn predicate on the "destination_location_id" field.
func DestinationLocationIDNotIn(vs ...uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldDestinationLocationID, vs...))
}

// DestinationLocationIDGT applies the GT predicate on the "destination_location_id" field.
func DestinationLocationIDGT(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldDestinationLocationID, v))
}

// DestinationLocationIDGTE applies the GTE predicate on the "destination_location_id" field.
func DestinationLocationIDGTE(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldDestinationLocationID, v))
}

// DestinationLocationIDLT applies the LT predicate on the "destination_location_id" field.
func DestinationLocationIDLT(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldDestinationLocationID, v))
}

// DestinationLocationIDLTE applies the LTE predicate on the "destination_location_id" field.
func DestinationLocationIDLTE(v uuid.UUID) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldDestinationLocationID, v))
}

// DestinationLocationIDIsNil applies the IsNil predicate on the "destination_location_id" field.
func DestinationLocationIDIsNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIsNull(FieldDestinationLocationID))
}

// DestinationLocationIDNotNil applies the NotNil predicate on the "destination_location_id" field.
func DestinationLocationIDNotNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotNull(FieldDestinationLocationID))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldQuantity, v))
}

// BeforeTotalEQ applies the EQ predicate on the "before_total" field.
func BeforeTotalEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldBeforeTotal, v))
}

// BeforeTotalNEQ applies the NEQ predicate on the "before_total" field.
func BeforeTotalNEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldBeforeTotal, v))
}

// BeforeTotalIn applies the In predicate on the "before_total" field.
func BeforeTotalIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldBeforeTotal, vs...))
}

// BeforeTotalNotIn applies the NotIn predicate on the "before_total" field.
func BeforeTotalNotIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldBeforeTotal, vs...))
}

// BeforeTotalGT applies the GT predicate on the "before_total" field.
func BeforeTotalGT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldBeforeTotal, v))
}

// BeforeTotalGTE applies the GTE predicate on the "before_total" field.
func BeforeTotalGTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldBeforeTotal, v))
}

// BeforeTotalLT applies the LT predicate on the "before_total" field.
func BeforeTotalLT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldBeforeTotal, v))
}

// BeforeTotalLTE applies the LTE predicate on the "before_total" field.
func BeforeTotalLTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldBeforeTotal, v))
}

// AfterTotalEQ applies the EQ predicate on the "after_total" field.
func AfterTotalEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldAfterTotal, v))
}

// AfterTotalNEQ applies the NEQ predicate on the "after_total" field.
func AfterTotalNEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldAfterTotal, v))
}

// AfterTotalIn applies the In predicate on the "after_total" field.
func AfterTotalIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldAfterTotal, vs...))
}

// AfterTotalNotIn applies the NotIn predicate on the "after_total" field.
func AfterTotalNotIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldAfterTotal, vs...))
}

// AfterTotalGT applies the GT predicate on the "after_total" field.
func AfterTotalGT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldAfterTotal, v))
}

// AfterTotalGTE applies the GTE predicate on the "after_total" field.
func AfterTotalGTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldAfterTotal, v))
}

// AfterTotalLT applies the LT predicate on the "after_total" field.
func AfterTotalLT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldAfterTotal, v))
}

// AfterTotalLTE applies the LTE predicate on the "after_total" field.
func AfterTotalLTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldAfterTotal, v))
}

// SourceBeforeEQ applies the EQ predicate on the "source_before" field.
func SourceBeforeEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldSourceBefore, v))
}

// SourceBeforeNEQ applies the NEQ predicate on the "source_before" field.
func SourceBeforeNEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldSourceBefore, v))
}

// SourceBeforeIn applies the In predicate on the "source_before" field.
func SourceBeforeIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldSourceBefore, vs...))
}

// SourceBeforeNotIn applies the NotIn predicate on the "source_before" field.
func SourceBeforeNotIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldSourceBefore, vs...))
}

// SourceBeforeGT applies the GT predicate on the "source_before" field.
func SourceBeforeGT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldSourceBefore, v))
}

// SourceBeforeGTE applies the GTE predicate on the "source_before" field.
func SourceBeforeGTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldSourceBefore, v))
}

// SourceBeforeLT applies the LT predicate on the "source_before" field.
func SourceBeforeLT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldSourceBefore, v))
}

// SourceBeforeLTE applies the LTE predicate on the "source_before" field.
func SourceBeforeLTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldSourceBefore, v))
}

// SourceBeforeIsNil applies the IsNil predicate on the "source_before" field.
func SourceBeforeIsNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIsNull(FieldSourceBefore))
}

// SourceBeforeNotNil applies the NotNil predicate on the "source_before" field.
func SourceBeforeNotNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotNull(FieldSourceBefore))
}

// SourceAfterEQ applies the EQ predicate on the "source_after" field.
func SourceAfterEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldSourceAfter, v))
}

// SourceAfterNEQ applies the NEQ predicate on the "source_after" field.
func SourceAfterNEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldSourceAfter, v))
}

// SourceAfterIn applies the In predicate on the "source_after" field.
func SourceAfterIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldSourceAfter, vs...))
}

// SourceAfterNotIn applies the NotIn predicate on the "source_after" field.
func SourceAfterNotIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldSourceAfter, vs...))
}

// SourceAfterGT applies the GT predicate on the "source_after" field.
func SourceAfterGT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldSourceAfter, v))
}

// SourceAfterGTE applies the GTE predicate on the "source_after" field.
func SourceAfterGTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldSourceAfter, v))
}

// SourceAfterLT applies the LT predicate on the "source_after" field.
func SourceAfterLT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldSourceAfter, v))
}

// SourceAfterLTE applies the LTE predicate on the "source_after" field.
func SourceAfterLTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldSourceAfter, v))
}

// SourceAfterIsNil applies the IsNil predicate on the "source_after" field.
func SourceAfterIsNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIsNull(FieldSourceAfter))
}

// SourceAfterNotNil applies the NotNil predicate on the "source_after" field.
func SourceAfterNotNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotNull(FieldSourceAfter))
}

// DestinationBeforeEQ applies the EQ predicate on the "destination_before" field.
func DestinationBeforeEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldDestinationBefore, v))
}

// DestinationBeforeNEQ applies the NEQ predicate on the "destination_before" field.
func DestinationBeforeNEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldDestinationBefore, v))
}

// DestinationBeforeIn applies the In predicate on the "destination_before" field.
func DestinationBeforeIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldDestinationBefore, vs...))
}

// DestinationBeforeNotIn applies the NotIn predicate on the "destination_before" field.
func DestinationBeforeNotIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldDestinationBefore, vs...))
}

// DestinationBeforeGT applies the GT predicate on the "destination_before" field.
func DestinationBeforeGT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldDestinationBefore, v))
}

// DestinationBeforeGTE applies the GTE predicate on the "destination_before" field.
func DestinationBeforeGTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldDestinationBefore, v))
}

// DestinationBeforeLT applies the LT predicate on the "destination_before" field.
func DestinationBeforeLT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldDestinationBefore, v))
}

// DestinationBeforeLTE applies the LTE predicate on the "destination_before" field.
func DestinationBeforeLTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldDestinationBefore, v))
}

// DestinationBeforeIsNil applies the IsNil predicate on the "destination_before" field.
func DestinationBeforeIsNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIsNull(FieldDestinationBefore))
}

// DestinationBeforeNotNil applies the NotNil predicate on the "destination_before" field.
func DestinationBeforeNotNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotNull(FieldDestinationBefore))
}

// DestinationAfterEQ applies the EQ predicate on the "destination_after" field.
func DestinationAfterEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldDestinationAfter, v))
}

// DestinationAfterNEQ applies the NEQ predicate on the "destination_after" field.
func DestinationAfterNEQ(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldDestinationAfter, v))
}

// DestinationAfterIn applies the In predicate on the "destination_after" field.
func DestinationAfterIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldDestinationAfter, vs...))
}

// DestinationAfterNotIn applies the NotIn predicate on the "destination_after" field.
func DestinationAfterNotIn(vs ...float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldDestinationAfter, vs...))
}

// DestinationAfterGT applies the GT predicate on the "destination_after" field.
func DestinationAfterGT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldDestinationAfter, v))
}

// DestinationAfterGTE applies the GTE predicate on the "destination_after" field.
func DestinationAfterGTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldDestinationAfter, v))
}

// DestinationAfterLT applies the LT predicate on the "destination_after" field.
func DestinationAfterLT(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldDestinationAfter, v))
}

// DestinationAfterLTE applies the LTE predicate on the "destination_after" field.
func DestinationAfterLTE(v float64) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldDestinationAfter, v))
}

// DestinationAfterIsNil applies the IsNil predicate on the "destination_after" field.
func DestinationAfterIsNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIsNull(FieldDestinationAfter))
}

// DestinationAfterNotNil applies the NotNil predicate on the "destination_after" field.
func DestinationAfterNotNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotNull(FieldDestinationAfter))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldContainsFold(FieldReason, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// RequestHashEQ applies the EQ predicate on the "request_hash" field.
func RequestHashEQ(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEQ(FieldRequestHash, v))
}

// RequestHashNEQ applies the NEQ predicate on the "request_hash" field.
func RequestHashNEQ(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNEQ(FieldRequestHash, v))
}

// RequestHashIn applies the In predicate on the "request_hash" field.
func RequestHashIn(vs ...string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldIn(FieldRequestHash, vs...))
}

// RequestHashNotIn applies the NotIn predicate on the "request_hash" field.
func RequestHashNotIn(vs ...string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldNotIn(FieldRequestHash, vs...))
}

// RequestHashGT applies the GT predicate on the "request_hash" field.
func RequestHashGT(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGT(FieldRequestHash, v))
}

// RequestHashGTE applies the GTE predicate on the "request_hash" field.
func RequestHashGTE(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldGTE(FieldRequestHash, v))
}

// RequestHashLT applies the LT predicate on the "request_hash" field.
func RequestHashLT(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLT(FieldRequestHash, v))
}

// RequestHashLTE applies the LTE predicate on the "request_hash" field.
func RequestHashLTE(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldLTE(FieldRequestHash, v))
}

// RequestHashContains applies the Contains predicate on the "request_hash" field.
func RequestHashContains(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldContains(FieldRequestHash, v))
}

// RequestHashHasPrefix applies the HasPrefix predicate on the "request_hash" field.
func RequestHashHasPrefix(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldHasPrefix(FieldRequestHash, v))
}

// RequestHashHasSuffix applies the HasSuffix predicate on the "request_hash" field.
func RequestHashHasSuffix(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldHasSuffix(FieldRequestHash, v))
}

// RequestHashEqualFold applies the EqualFold predicate on the "request_hash" field.
func RequestHashEqualFold(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldEqualFold(FieldRequestHash, v))
}

// RequestHashContainsFold applies the ContainsFold predicate on the "request_hash" field.
func RequestHashContainsFold(v string) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.FieldContainsFold(FieldRequestHash, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEntity applies the HasEdge predicate on the "entity" edge.
func HasEntity() predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EntityTable, EntityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntityWith applies the HasEdge predicate on the "entity" edge with a given conditions (other predicates).
func HasEntityWith(preds ...predicate.Entity) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(func(s *sql.Selector) {
		step := newEntityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EntityStockTransaction) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EntityStockTransaction) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EntityStockTransaction) predicate.EntityStockTransaction {
	return predicate.EntityStockTransaction(sql.NotPredicates(p))
}
