// Code generated by ent, DO NOT EDIT.

package locationlayoutelement

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the locationlayoutelement type in the database.
	Label = "location_layout_element"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldX holds the string denoting the x field in the database.
	FieldX = "x"
	// FieldY holds the string denoting the y field in the database.
	FieldY = "y"
	// FieldWidth holds the string denoting the width field in the database.
	FieldWidth = "width"
	// FieldHeight holds the string denoting the height field in the database.
	FieldHeight = "height"
	// FieldEndX holds the string denoting the end_x field in the database.
	FieldEndX = "end_x"
	// FieldEndY holds the string denoting the end_y field in the database.
	FieldEndY = "end_y"
	// FieldRotation holds the string denoting the rotation field in the database.
	FieldRotation = "rotation"
	// FieldZOrder holds the string denoting the z_order field in the database.
	FieldZOrder = "z_order"
	// EdgeLayout holds the string denoting the layout edge name in mutations.
	EdgeLayout = "layout"
	// EdgeTarget holds the string denoting the target edge name in mutations.
	EdgeTarget = "target"
	// Table holds the table name of the locationlayoutelement in the database.
	Table = "location_layout_elements"
	// LayoutTable is the table that holds the layout relation/edge.
	LayoutTable = "location_layout_elements"
	// LayoutInverseTable is the table name for the LocationLayout entity.
	// It exists in this package in order to avoid circular dependency with the "locationlayout" package.
	LayoutInverseTable = "location_layouts"
	// LayoutColumn is the table column denoting the layout relation/edge.
	LayoutColumn = "location_layout_elements"
	// TargetTable is the table that holds the target relation/edge.
	TargetTable = "location_layout_elements"
	// TargetInverseTable is the table name for the Entity entity.
	// It exists in this package in order to avoid circular dependency with the "entity" package.
	TargetInverseTable = "entities"
	// TargetColumn is the table column denoting the target relation/edge.
	TargetColumn = "entity_layout_placements"
)

// Columns holds all SQL columns for locationlayoutelement fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldKind,
	FieldX,
	FieldY,
	FieldWidth,
	FieldHeight,
	FieldEndX,
	FieldEndY,
	FieldRotation,
	FieldZOrder,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "location_layout_elements"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"entity_layout_placements",
	"location_layout_elements",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultWidth holds the default value on creation for the "width" field.
	DefaultWidth float64
	// DefaultHeight holds the default value on creation for the "height" field.
	DefaultHeight float64
	// DefaultEndX holds the default value on creation for the "end_x" field.
	DefaultEndX float64
	// DefaultEndY holds the default value on creation for the "end_y" field.
	DefaultEndY float64
	// DefaultRotation holds the default value on creation for the "rotation" field.
	DefaultRotation float64
	// DefaultZOrder holds the default value on creation for the "z_order" field.
	DefaultZOrder int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindWall     Kind = "wall"
	KindLocation Kind = "location"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindWall, KindLocation:
		return nil
	default:
		return fmt.Errorf("locationlayoutelement: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the LocationLayoutElement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByX orders the results by the x field.
func ByX(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldX, opts...).ToFunc()
}

// ByY orders the results by the y field.
func ByY(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldY, opts...).ToFunc()
}

// ByWidth orders the results by the width field.
func ByWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWidth, opts...).ToFunc()
}

// ByHeight orders the results by the height field.
func ByHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeight, opts...).ToFunc()
}

// ByEndX orders the results by the end_x field.
func ByEndX(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndX, opts...).ToFunc()
}

// ByEndY orders the results by the end_y field.
func ByEndY(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndY, opts...).ToFunc()
}

// ByRotation orders the results by the rotation field.
func ByRotation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRotation, opts...).ToFunc()
}

// ByZOrder orders the results by the z_order field.
func ByZOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldZOrder, opts...).ToFunc()
}

// ByLayoutField orders the results by layout field.
func ByLayoutField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLayoutStep(), sql.OrderByField(field, opts...))
	}
}

// ByTargetField orders the results by target field.
func ByTargetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetStep(), sql.OrderByField(field, opts...))
	}
}
func newLayoutStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LayoutInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LayoutTable, LayoutColumn),
	)
}
func newTargetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TargetTable, TargetColumn),
	)
}
