// Code generated by ent, DO NOT EDIT.

package locationlayoutelement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldUpdatedAt, v))
}

// X applies equality check predicate on the "x" field. It's identical to XEQ.
func X(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldX, v))
}

// Y applies equality check predicate on the "y" field. It's identical to YEQ.
func Y(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldY, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldHeight, v))
}

// EndX applies equality check predicate on the "end_x" field. It's identical to EndXEQ.
func EndX(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldEndX, v))
}

// EndY applies equality check predicate on the "end_y" field. It's identical to EndYEQ.
func EndY(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldEndY, v))
}

// Rotation applies equality check predicate on the "rotation" field. It's identical to RotationEQ.
func Rotation(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldRotation, v))
}

// ZOrder applies equality check predicate on the "z_order" field. It's identical to ZOrderEQ.
func ZOrder(v int) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldZOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLTE(FieldUpdatedAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNotIn(FieldKind, vs...))
}

// XEQ applies the EQ predicate on the "x" field.
func XEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldX, v))
}

// XNEQ applies the NEQ predicate on the "x" field.
func XNEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNEQ(FieldX, v))
}

// XIn applies the In predicate on the "x" field.
func XIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldIn(FieldX, vs...))
}

// XNotIn applies the NotIn predicate on the "x" field.
func XNotIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNotIn(FieldX, vs...))
}

// XGT applies the GT predicate on the "x" field.
func XGT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGT(FieldX, v))
}

// XGTE applies the GTE predicate on the "x" field.
func XGTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGTE(FieldX, v))
}

// XLT applies the LT predicate on the "x" field.
func XLT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLT(FieldX, v))
}

// XLTE applies the LTE predicate on the "x" field.
func XLTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLTE(FieldX, v))
}

// YEQ applies the EQ predicate on the "y" field.
func YEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldY, v))
}

// YNEQ applies the NEQ predicate on the "y" field.
func YNEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNEQ(FieldY, v))
}

// YIn applies the In predicate on the "y" field.
func YIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldIn(FieldY, vs...))
}

// YNotIn applies the NotIn predicate on the "y" field.
func YNotIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNotIn(FieldY, vs...))
}

// YGT applies the GT predicate on the "y" field.
func YGT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGT(FieldY, v))
}

// YGTE applies the GTE predicate on the "y" field.
func YGTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGTE(FieldY, v))
}

// YLT applies the LT predicate on the "y" field.
func YLT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLT(FieldY, v))
}

// YLTE applies the LTE predicate on the "y" field.
func YLTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLTE(FieldY, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLTE(FieldWidth, v))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLTE(FieldHeight, v))
}

// EndXEQ applies the EQ predicate on the "end_x" field.
func EndXEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldEndX, v))
}

// EndXNEQ applies the NEQ predicate on the "end_x" field.
func EndXNEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNEQ(FieldEndX, v))
}

// EndXIn applies the In predicate on the "end_x" field.
func EndXIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldIn(FieldEndX, vs...))
}

// EndXNotIn applies the NotIn predicate on the "end_x" field.
func EndXNotIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNotIn(FieldEndX, vs...))
}

// EndXGT applies the GT predicate on the "end_x" field.
func EndXGT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGT(FieldEndX, v))
}

// EndXGTE applies the GTE predicate on the "end_x" field.
func EndXGTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGTE(FieldEndX, v))
}

// EndXLT applies the LT predicate on the "end_x" field.
func EndXLT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLT(FieldEndX, v))
}

// EndXLTE applies the LTE predicate on the "end_x" field.
func EndXLTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLTE(FieldEndX, v))
}

// EndYEQ applies the EQ predicate on the "end_y" field.
func EndYEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldEndY, v))
}

// EndYNEQ applies the NEQ predicate on the "end_y" field.
func EndYNEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNEQ(FieldEndY, v))
}

// EndYIn applies the In predicate on the "end_y" field.
func EndYIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldIn(FieldEndY, vs...))
}

// EndYNotIn applies the NotIn predicate on the "end_y" field.
func EndYNotIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNotIn(FieldEndY, vs...))
}

// EndYGT applies the GT predicate on the "end_y" field.
func EndYGT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGT(FieldEndY, v))
}

// EndYGTE applies the GTE predicate on the "end_y" field.
func EndYGTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGTE(FieldEndY, v))
}

// EndYLT applies the LT predicate on the "end_y" field.
func EndYLT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLT(FieldEndY, v))
}

// EndYLTE applies the LTE predicate on the "end_y" field.
func EndYLTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLTE(FieldEndY, v))
}

// RotationEQ applies the EQ predicate on the "rotation" field.
func RotationEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldRotation, v))
}

// RotationNEQ applies the NEQ predicate on the "rotation" field.
func RotationNEQ(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNEQ(FieldRotation, v))
}

// RotationIn applies the In predicate on the "rotation" field.
func RotationIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldIn(FieldRotation, vs...))
}

// RotationNotIn applies the NotIn predicate on the "rotation" field.
func RotationNotIn(vs ...float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNotIn(FieldRotation, vs...))
}

// RotationGT applies the GT predicate on the "rotation" field.
func RotationGT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGT(FieldRotation, v))
}

// RotationGTE applies the GTE predicate on the "rotation" field.
func RotationGTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGTE(FieldRotation, v))
}

// RotationLT applies the LT predicate on the "rotation" field.
func RotationLT(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLT(FieldRotation, v))
}

// RotationLTE applies the LTE predicate on the "rotation" field.
func RotationLTE(v float64) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLTE(FieldRotation, v))
}

// ZOrderEQ applies the EQ predicate on the "z_order" field.
func ZOrderEQ(v int) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldEQ(FieldZOrder, v))
}

// ZOrderNEQ applies the NEQ predicate on the "z_order" field.
func ZOrderNEQ(v int) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNEQ(FieldZOrder, v))
}

// ZOrderIn applies the In predicate on the "z_order" field.
func ZOrderIn(vs ...int) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldIn(FieldZOrder, vs...))
}

// ZOrderNotIn applies the NotIn predicate on the "z_order" field.
func ZOrderNotIn(vs ...int) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldNotIn(FieldZOrder, vs...))
}

// ZOrderGT applies the GT predicate on the "z_order" field.
func ZOrderGT(v int) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGT(FieldZOrder, v))
}

// ZOrderGTE applies the GTE predicate on the "z_order" field.
func ZOrderGTE(v int) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldGTE(FieldZOrder, v))
}

// ZOrderLT applies the LT predicate on the "z_order" field.
func ZOrderLT(v int) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLT(FieldZOrder, v))
}

// ZOrderLTE applies the LTE predicate on the "z_order" field.
func ZOrderLTE(v int) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.FieldLTE(FieldZOrder, v))
}

// HasLayout applies the HasEdge predicate on the "layout" edge.
func HasLayout() predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LayoutTable, LayoutColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLayoutWith applies the HasEdge predicate on the "layout" edge with a given conditions (other predicates).
func HasLayoutWith(preds ...predicate.LocationLayout) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(func(s *sql.Selector) {
		step := newLayoutStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTarget applies the HasEdge predicate on the "target" edge.
func HasTarget() predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TargetTable, TargetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetWith applies the HasEdge predicate on the "target" edge with a given conditions (other predicates).
func HasTargetWith(preds ...predicate.Entity) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(func(s *sql.Selector) {
		step := newTargetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LocationLayoutElement) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LocationLayoutElement) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LocationLayoutElement) predicate.LocationLayoutElement {
	return predicate.LocationLayoutElement(sql.NotPredicates(p))
}
